#pragma once
#include<vector>

struct VehiclePreview {
	std::wstring VName;
	char* VCode;
	char* TexDict;
	char* TexName;
};


static std::vector<VehiclePreview> Super{
{L"811","Pfister811","lgm_dlc_executive1","pfister811"},
{L"Adder","Adder","lgm_default","adder"},
{L"Autarch","autarch","lgm_dlc_xmas2017","autarch_b"},
{L"Banshee 900R","Banshee2","lsc_jan2016","banshee2"},
{L"Bullet","Bullet","lgm_default","bullet"},
{L"Cheetah","Cheetah","lgm_default","cheetah"},
{L"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{L"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{L"Deveste","DEVESTE","lgm_dlc_arena","deveste"},
{L"ETR1","Sheava","lgm_dlc_stunt","sheava"},
{L"Emerus","emerus","lgm_dlc_vinewood","emerus"},
{L"Entity 2","entity2","lgm_dlc_assault","entity2"},
{L"Entity XF","Entityxf","lgm_default","entityxf"},
{L"FMJ","Fmj","lgm_dlc_executive1","fmj"},
{L"Furia","furia","lgm_dlc_casinoheist","furia"},
{L"GP1","gp1","lgm_dlc_specialraces","gp1"},
{L"Infernus","Infernus","sssa_default","infernus"},
{L"Itali GTB Custom","italigtb2","lsc_dlc_import_export","italigtb2"},
{L"Itali GTB","Italigtb","lsc_dlc_import_export","italigtb"},
{L"Krieger","krieger","lgm_dlc_vinewood","krieger"},
{L"Nero Custom","Nero2","lsc_dlc_import_export","nero2_b"},
{L"Nero","Nero","lsc_dlc_import_export","nero2_a"},
{L"Osiris","Osiris","lgm_dlc_luxe","Osiris"},
{L"Penetrator","Penetrator","lgm_dlc_importexport","penetrator"},
{L"RE-7B","Le7b","lgm_dlc_stunt","le7b"},
{L"Reaper","Reaper","lgm_dlc_executive1","reaper"},
{L"Rocket Voltic","voltic2","candc_importexport","voltic2"},
{L"S80","s80","lgm_dlc_vinewood","s80"},
{L"Sc1","sc1","lgm_dlc_xmas2017","sc1_b"},
{L"Scramjet","Scramjet","candc_battle","scramjet"},
{L"Sultan RS","Sultanrs","lsc_jan2016","sultan2_a"},
{L"T20","T20","lgm_dlc_luxe","t20"},
{L"Taipan","taipan","lgm_dlc_assault","taipan"},
{L"Tempesta","Tempesta","lgm_dlc_importexport","tempesta"},
{L"Tezeract","tezeract","lgm_dlc_assault","tezeract"},
{L"Thrax","thrax","lgm_dlc_vinewood","thrax"},
{L"Turismo R","turismor","lgm_dlc_business","turismor"},
{L"Tyrant","TYRANT","lgm_dlc_assault","tyrant"},
{L"Tyrus","Tyrus","lgm_dlc_stunt","tyrus"},
{L"Vacca","Vacca","lgm_default","vacca"},
{L"Vagner","Vagner","lgm_dlc_gunrunning","vagner"},
{L"Vigilante","Vigilante","candc_smuggler","vigilante"},
{L"Visione","visione","lgm_dlc_smuggler","visione"},
{L"Voltic","Voltic","lgm_default","voltic_tless"},
{L"X80 Proto","Prototipo","lgm_dlc_executive1","prototipo"},
{L"XA21","xa21","lgm_dlc_gunrunning","xa21"},
{L"Zentorno","Zentorno","lgm_dlc_business2","zentorno"},
{L"Zorrusso","zorrusso","lgm_dlc_vinewood","zorrusso"}
};
static std::vector<VehiclePreview> Sports{
{L"Alpha","Alpha","lgm_dlc_business","alpha"},
{L"Banshee","Banshee","lgm_dlc_business2","banshee_tless"},
{L"Bestia Compact","Blista2","sssa_dlc_mp_to_sp","blista2"},
{L"Bestia GTS","Bestiagts","lgm_dlc_executive1","bestiagts"},
{L"Blista Compact (Race)","blista3","",""},
{L"Buffalo S","Buffalo2","sssa_dlc_hipster","buffalo"},
{L"Buffalo Sprunk","Buffalo3","sssa_dlc_mp_to_sp","buffalo3"},
{L"Buffalo","Buffalo","sssa_dlc_hipster","buffalo"},
{L"Carbonizzare","Carbonizzare","lgm_default","carboniz"},
{L"Comet Retro Custom","Comet3","lsc_dlc_import_export","comet3"},
{L"Comet","Comet2","sssa_default","comet2"},
{L"Comet4","comet4","lgm_dlc_xmas2017","comet4_b"},
{L"Comet5","comet5","lgm_dlc_xmas2017","comet5_b"},
{L"Coquette","Coquette","lgm_default","coquette"},
{L"Drafter","drafter","lgm_dlc_vinewood","drafter"},
{L"Drift Tampa","tampa2","sssa_dlc_stunt","tampa2"},
{L"Elegy RH8","Elegy2","lgm_default","elegy2"},
{L"Elegy Retro Custom","Elegy","lsc_dlc_import_export","elegy"},
{L"Feltzer 2","Feltzer2","",""},
{L"Formula PR4", "formula", "lgm_dlc_casinoheist", "formula"},
{L"Formula2 R88", "formula2", "lgm_dlc_casinoheist", "formula2"},
{L"Flash GT","flashgt","lgm_dlc_assault","flashgt"},
{L"Furore GT","Furoregt","lgm_dlc_lts_creator","furore"},
{L"Fusilade","Fusilade","sssa_dlc_business2","fusilade"},
{L"Futo","futo","sssa_dlc_battle","futo"},
{L"GB200","gb200","lgm_dlc_assault","gb200"},
{L"Hotring","hotring","sssa_dlc_assault","hotring"},
{L"Imorgon","imorgon","lgm_dlc_casinoheist","imorgon"},
{L"Issi 7","issi7","sssa_dlc_vinewood","issi7"},
{L"Italigto","ITALIGTO","lgm_dlc_arena","italigto"},
{L"Jester (Race)","jester2","sssa_dlc_christmas_2","jester2"},
{L"Jester 3","jester3","lgm_dlc_assault","jester3"},
{L"Jester","Jester","lgm_dlc_business","jester"},
{L"Jugular","jugular","lgm_dlc_vinewood","jugular"},
{L"Khamelion","Khamelion","",""},
{L"Komoda","komoda","lgm_dlc_casinoheist","komoda"},
{L"Kuruma Armored","kuruma2","sssa_dlc_heist","kuruma2"},
{L"Kuruma","kuruma","sssa_dlc_heist","kuruma"},
{L"Locust","locust","lgm_dlc_vinewood","locust"},
{L"Lynx","lynx","lgm_dlc_stunt","lynx"},
{L"Massacro (Race)","Massacro2","sssa_dlc_christmas_2","massacro2"},
{L"Massacro","Massacro","lgm_dlc_business2","massacro"},
{L"Neo","neo","lgm_dlc_vinewood","neo"},
{L"Neon","neon","lgm_dlc_xmas2017","neon_b"},
{L"Obey 9F Cabrio","Ninef2","lgm_default","ninef2"},
{L"Obey","Ninef","sssa_default","ninef"},
{L"Omnis","Omnis","sssa_dlc_stunt","omnis"},
{L"Paragon","paragon","lgm_dlc_vinewood","paragon"},
{L"Paragon (Armored)","paragon2","lgm_dlc_vinewood","paragon"},
{L"Pariah","pariah","lgm_dlc_xmas2017","pariah_b"},
{L"Penumbra","Penumbra","sssa_dlc_business2","penumbra"},
{L"Raiden","raiden","lgm_dlc_xmas2017","raiden_b"},
{L"Rapid GT Cabrio","rapidgt2","lgm_default","rapidgt2"},
{L"Rapid GT","Rapidgt","lgm_default","rapidgt"},
{L"Raptor","raptor","lgm_dlc_biker","raptor"},
{L"Revolter","revolter","lgm_dlc_xmas2017","revolter_b"},
{L"Ruston","ruston","lgm_dlc_specialraces","ruston"},
{L"Schafter LWB","schafter4","lgm_dlc_apartments","schafter4"},
{L"Schafter V12","schafter3","lgm_dlc_apartments","schafter3"},
{L"Schlagen","SCHLAGEN","lgm_dlc_arena","schlagen"},
{L"Schwarzer","schwarzer","sssa_default","schwarze"},
{L"Sentinel Classic","sentinel3","sssa_dlc_xmas2017","sentinel3_b"},
{L"Seven 70","Seven70","lgm_dlc_executive1","seven70"},
{L"Specter","specter","lsc_dlc_import_export","specter2_a"},
{L"Specter2","specter2","lsc_dlc_import_export","specter2_b"},
{L"Streiter","streiter","lgm_dlc_xmas2017","streiter_b"},
{L"Sugoi","sugoi","sssa_dlc_casinoheist","sugoi"},
{L"Sultan","Sultan","lsc_jan2016","sultan2_a"},
{L"Sultan2","sultan2","sssa_dlc_casinoheist","sultan2"},
{L"Surano","surano","lgm_default","surano_convertable"},
{L"Tropos","tropos","sssa_dlc_stunt","tropos"},
{L"V-STR","vstr","lgm_dlc_casinoheist","vstr"},
{L"Verlierer","Verlierer2","lgm_dlc_apartments","verlier"},
{L"Zr380 2","ZR3802","mba_vehicles","zr3802"},
{L"Zr380 3","ZR3803","mba_vehicles","zr3803"},
{L"Zr380","ZR380","mba_vehicles","zr3801"}
};
static std::vector<VehiclePreview> SportsClassics{
{L"Ardent","Ardent","candc_gunrunning","ardent"},
{L"Casco","casco","lgm_dlc_heist","casco"},
{L"Cheburek","cheburek","sssa_dlc_assault","cheburek"},
{L"Cheetah 2","Cheetah2","lgm_dlc_gunrunning","cheetah2"},
{L"Coquette Classic","coquette2","lgm_dlc_pilot","coquette2"},
{L"Deluxo","deluxo","candc_xmas2017","deluxo_b"},
{L"Dynasty","dynasty","sssa_dlc_vinewood","dynasty"},
{L"Fagaloa","fagaloa","sssa_dlc_assault","fagaloa"},
{L"Gt500","gt500","lgm_dlc_xmas2017","gt500_b"},
{L"Infernus Classic","Infernus2","lgm_dlc_specialraces","infernus2"},
{L"JB700","jb700","lgm_default","jb700"},
{L"JB700W","jb7002","lgm_default","jb700"},
{L"Mamba","mamba","lgm_dlc_apartments","mamba"},
{L"Manana","manana","",""},
{L"Michelli","michelli","sssa_dlc_assault","michelli"},
{L"Monroe","monroe","lgm_default","monroe"},
{L"Nebula","nebula","sssa_dlc_vinewood","nebula"},
{L"Peyote","Peyote","",""},
{L"Pigalle","pigalle","sssa_dlc_hipster","pigalle"},
{L"Rapid GT 3","rapidgt3","lgm_dlc_smuggler","rapidgt3"},
{L"Retinue 2","retinue2","sssa_dlc_casinoheist","retinue2"},
{L"Retinue","Retinue","",""},
{L"Retinue","Retinue","sssa_dlc_smuggler","retinue_b"},
{L"Roosevelt (Halloween)","btype2","sssa_dlc_halloween","btype2"},
{L"Roosevelt Valor","btype3","lgm_dlc_valentines2","roosevelt2"},
{L"Roosevelt","btype","lgm_dlc_valentines","roosevelt"},
{L"Savestra","savestra","lgm_dlc_xmas2017","savestra_b"},
{L"Stinger GT","stingergt","lgm_default","stingerg"},
{L"Stinger","stinger","lgm_default","stinger"},
{L"Stirling GT","Feltzer3","lgm_dlc_luxe","feltzer3"},
{L"Stromberg","stromberg","candc_xmas2017","stromberg_b"},
{L"Swinger","Swinger","lgm_dlc_battle","swinger"},
{L"Torero","torero","lgm_dlc_gunrunning","torero"},
{L"Tornado","Tornado","",""},
{L"Tornado 2 Cabrio","Tornado2","",""},
{L"Tornado 3(Rusty)","Tornado3","",""},
{L"Tornado 4 Cabrio (Rusty)","Tornado4","",""},
{L"Tornado 5","Tornado5","lsc_lowrider2","tornado5_a"},
{L"Tornado 6 Rat","tornado6","sssa_dlc_biker","tornado6"},
{L"Turismo Classic","turismo2","lgm_dlc_specialraces","turismo2"},
{L"Viseris","viseris","lgm_dlc_xmas2017","viseris_b"},
{L"Z-Type","ztype","lgm_default","ztype"},
{L"Z190","z190","lgm_dlc_xmas2017","z190_b"},
{L"Zion 3","zion3","sssa_dlc_vinewood","zion3"}
};
static std::vector<VehiclePreview> Coupes{
{L"Cognoscenti Cabrio","cogcabrio","lgm_default","cogcabri"},
{L"Exemplar","Exemplar","sssa_default","exemplar"},
{L"F620","F620","sssa_dlc_business2","f620"},
{L"Felon","Felon","sssa_default","felon"},
{L"Felon Topless","Felon2","sssa_default","felon2"},
{L"Jackal","Jackal","sssa_dlc_heist","jackal"},
{L"Oracle","Oracle","sssa_default","oracle"},
{L"Oracle 2","oracle2","sssa_dlc_heist","oracle1"},
{L"Sentinel XS","Sentinel","sssa_dlc_business2","sentinel"},
{L"Sentinel","Sentinel2","sssa_dlc_business2","sentinel"},
{L"Windsor","Windsor","lgm_dlc_luxe","windsor"},
{L"Windsor Drop","Windsor2","",""},
{L"Zion","Zion","sssa_default","zion"},
{L"Zion Cabrio","Zion2","sssa_default","zion2"}
};
static std::vector<VehiclePreview> Muscle{
{L"Blade","Blade","sssa_dlc_hipster","blade"},
{L"Broken Ruiner","ruiner3","",""},
{L"Buccaneer Custom","Buccaneer2","lsc_default","buccaneer2_b"},
{L"Buccaneer","Buccaneer","lsc_default","buccaneer2_a"},
{L"Chino 2","Chino2","lsc_default","chino2_a"},
{L"Chino","Chino","lgm_dlc_luxe","chino"},
{L"Clique","CLIQUE","lgm_dlc_arena","clique"},
{L"Coquette Classic","coquette3","lgm_dlc_luxe","coquette3"},
{L"Deviant","DEVIANT","lgm_dlc_arena","deviant"},
{L"Dominator 3","dominator3","sssa_dlc_assault","dominator3"},
{L"Dominator 4","DOMINATOR4","mba_vehicles","dominato_c_1"},
{L"Dominator 5","DOMINATOR5","mba_vehicles","dominato_c_2"},
{L"Dominator 6","DOMINATOR6","mba_vehicles","dominato_c_3"},
{L"Dominator","Dominator","sssa_dlc_business2","dominato"},
{L"Duke O' Death","Dukes2","candc_default","dukes"},
{L"Dukes","Dukes","sssa_dlc_mp_to_sp","dukes"},
{L"Ellie","ellie","sssa_dlc_assault","ellie"},
{L"Faction Custom 2","Faction3","lsc_lowrider2","faction3_b"},
{L"Faction Custom","Faction2","lsc_lowrider2","faction3_a"},
{L"Faction","Faction","lsc_default","faction2_a"},
{L"Gauntlet (Race)","Gauntlet2","sssa_dlc_mp_to_sp","gauntlet2"},
{L"Gauntlet 3","gauntlet3","sssa_dlc_vinewood","gauntlet3"},
{L"Gauntlet 4","gauntlet4","sssa_dlc_vinewood","gauntlet4"},
{L"Gauntlet","Gauntlet","sssa_default","gauntlet"},
{L"Hermes","hermes","sssa_dlc_xmas2017","hermes_b"},
{L"Hotknife","Hotknife","lgm_default","hotknife"},
{L"Hustler","hustler","lgm_dlc_xmas2017","hustler_b"},
{L"Impaler","IMPALER","mba_vehicles","impaler"},
{L"Impaler","impaler","sssa_dlc_vinewood","impaler"},
{L"Impaler2","IMPALER2","mba_vehicles","impaler_c_1"},
{L"Impaler3","IMPALER3","mba_vehicles","impaler_c_2"},
{L"Impaler4","IMPALER4","mba_vehicles","impaler_c_3"},
{L"Imperator 2","IMPERATOR2","mba_vehicles","imperator2"},
{L"Imperator 3","IMPERATOR3","mba_vehicles","imperator3"},
{L"Imperator","IMPERATOR","mba_vehicles","imperator1"},
{L"Lurcher","lurcher","sssa_dlc_halloween","lurcher"},
{L"Moonbeam Custom","Moonbeam2","lsc_default","moonbeam2"},
{L"Moonbeam","Moonbeam","",""},
{L"Nightshade","nightshade","lgm_dlc_apartments","niteshad"},
{L"Peyote 2","peyote2","sssa_dlc_vinewood","peyote2"},
{L"Phoenix","phoenix","",""},
{L"Picador","picador","sssa_dlc_hipster","picador"},
{L"Pisswasser Dominator","Dominator2","sssa_dlc_mp_to_sp","dominator2"},
{L"Ratloader (Rusty)","ratloader","sssa_dlc_valentines","rloader"},
{L"Ratloader","ratloader2","sssa_dlc_christmas_2","rloader2"},
{L"Ruiner 2000","ruiner2","candc_importexport","ruiner2"},
{L"Ruiner","ruiner","sssa_dlc_battle","ruiner"},
{L"Sabre Turbo","Sabregt","",""},
{L"Sabre","Sabregt2","lsc_lowrider2","sabregt2_a"},
{L"Slamvan (Lost MC)","Slamvan2","",""},
{L"Slamvan 3","Slamvan3","lsc_lowrider2","slamvan3_b"},
{L"Slamvan 4","SLAMVAN4","mba_vehicles","slamvan_c_1"},
{L"Slamvan 5","SLAMVAN5","mba_vehicles","slamvan_c_2"},
{L"Slamvan 6","SLAMVAN6","mba_vehicles","slamvan_c_3"},
{L"Slamvan","Slamvan","sssa_dlc_christmas_2","slamvan"},
{L"Stalion (Race)","stalion2","sssa_dlc_mp_to_sp","stalion2"},
{L"Stalion","Stalion","sssa_dlc_mp_to_sp","stallion"},
{L"Tampa 3","tampa3","candc_gunrunning","tampa3"},
{L"Tampa","Tampa","sssa_dlc_christmas_3","tampa"},
{L"Tulip","TULIP","sssa_dlc_arena","tulip"},
{L"Vamos","VAMOS","sssa_dlc_arena","vamos"},
{L"Vigero","Vigero","sssa_default","vigero"},
{L"Virgo Classic","Virgo2","lsc_lowrider2","virgo2_a"},
{L"Virgo Custom","Virgo3","lsc_lowrider2","virgo2_b"},
{L"Virgo","Virgo","lgm_dlc_luxe","virgo"},
{L"Voodoo Custom","Voodoo2","lsc_default","voodoo_b"},
{L"Voodoo","Voodoo","lsc_default","voodoo_a"},
{L"Yosemite","yosemite","sssa_dlc_xmas2017","yosemite_b"},
{L"Yosemite","yosemite2","sssa_dlc_casinoheist","yosemite2"}
};
static std::vector<VehiclePreview> Offroad{
{L"BF Injection","bfinjection","sssa_default","bfinject"},
{L"Bifta","Bifta","sssa_default","bifta"},
{L"Blazer (Trevor's)","Blazer3","sssa_dlc_hipster","blazer3"},
{L"Blazer Aqua","Blazer5","candc_importexport","blazer5"},
{L"Blazer lifeguard","Blazer2","",""},
{L"Blazer","Blazer","sssa_default","blazer"},
{L"Blazer4","Blazer4","sssa_dlc_biker","blazer4"},
{L"Bodhi","Bodhi2","sssa_default","bodhi2"},
{L"Brawler","Brawler","lgm_dlc_luxe","brawler"},
{L"Bruiser 2","BRUISER2","mba_vehicles","bruiser_c_2"},
{L"Bruiser 3","BRUISER3","mba_vehicles","bruiser_c_3"},
{L"Bruiser","BRUISER","mba_vehicles","bruiser_c_1"},
{L"Brutus 2","BRUTUS2","mba_vehicles","brutus2"},
{L"Brutus 3","BRUTUS3","mba_vehicles","brutus3"},
{L"Brutus","BRUTUS","mba_vehicles","brutus1"},
{L"Caracara 2","caracara2","sssa_dlc_vinewood","caracara2"},
{L"Caracara","caracara","candc_assault","caracara"},
{L"Dubsta 6x6","Dubsta3","candc_default","dubsta3"},
{L"Dune (Gunrunning)","Dune3","candc_gunrunning","dune3"},
{L"Dune Buggy","Dune","sssa_default","dune"},
{L"Duneloader","Dloader","",""},
{L"Everon","everon","sssa_dlc_casinoheist","everon"},
{L"Freecrawler","Freecrawler","lgm_dlc_battle","freecrawler"},
{L"Hellion","hellion","sssa_dlc_vinewood","hellion"},
{L"Insurgent 3","Insurgent3","",""},
{L"Insurgent 3","Insurgent3","ua_generic","ua_unlock_11"},
{L"Insurgent Pick-Up","Insurgent","candc_default","insurgent"},
{L"Insurgent","Insurgent2","candc_default","insurgent"},
{L"Kalahari","Kalahari","sssa_default","kalahari"},
{L"Kamacho","kamacho","sssa_dlc_xmas2017","kamacho_b"},
{L"Marshall","marshall","candc_default","marshall"},
{L"Menacer","Menacer","candc_battle","menacer"},
{L"Mesa","Mesa3","candc_default","mesa3"},
{L"Monster 3","MONSTER3","mba_vehicles","monster_c_1"},
{L"Monster 4","MONSTER4","mba_vehicles","monster_c_2"},
{L"Monster 5","MONSTER5","mba_vehicles","monster_c_3"},
{L"Night Shark","nightshark","candc_gunrunning","nightshark"},
{L"Outlaw","outlaw","sssa_dlc_casinoheist","outlaw"},
{L"Ramp Buggy (Roof)","Dune4","",""},
{L"Ramp Buggy","Dune5","candc_importexport","dune5"},
{L"Rancher XL 2","Rancherxl2","",""},
{L"Rancher XL","Rancherxl","sssa_dlc_business","rancherx"},
{L"Rcbandito","RCBANDITO","sssa_dlc_arena","rcbandito"},
{L"Rebel (Rusty)","Rebel2","sssa_dlc_hipster","rebel2"},
{L"Rebel","Rebel","sssa_default","rebel"},
{L"Riata","riata","sssa_dlc_xmas2017","riata_b"},
{L"Sandking XL","Sandking","sssa_default","sandking_b"},
{L"Sandking","Sandking2","sssa_default","sandkin_2b"},
{L"Space Docker","Dune2","",""},
{L"Technical 3","Technical3","",""},
{L"Technical Aqua","Technical2","candc_importexport","technical2"},
{L"Technical Custom","Technical3","ua_generic","ua_unlock_15"},
{L"Technical","Technical","candc_default","technical"},
{L"The Liberator","monster","candc_default","monster"},
{L"Trophy Truck 2","TrophyTruck2","sssa_dlc_stunt","trophy2"},
{L"Trophy Truck","TrophyTruck","sssa_dlc_stunt","trophy"},
{L"Vagrant","vagrant","sssa_dlc_casinoheist","vagrant"},
{L"Zhaba","Zhaba","",""},

};
static std::vector<VehiclePreview> Motorcycles{
{L"Akuma","Akuma","sssa_default","akuma"},
{L"Avarus","Avarus","sssa_dlc_biker","avarus"},
{L"BF400","BF400","sssa_dlc_stunt","bf400"},
{L"Bagger","Bagger","sssa_dlc_biker","bagger"},
{L"Bati 801R","BATI2","sssa_default","bati2"},
{L"Bati","BATI","sssa_default","bati"},
{L"Carbon RS","CARBONRS","lgm_default","carbon"},
{L"Chimera","CHIMERA","sssa_dlc_biker","chimera"},
{L"Cliffhanger","CLIFFHANGER","sssa_dlc_stunt","cliffhanger"},
{L"Daemon 2","DAEMON2","sssa_dlc_biker","daemon2"},
{L"Daemon","DAEMON","",""},
{L"Deathbike 2","DEATHBIKE2","mba_vehicles","deathbike_c_2"},
{L"Deathbike 3","DEATHBIKE3","mba_vehicles","deathbike_c_3"},
{L"Deathbike","DEATHBIKE","mba_vehicles","deathbike_c_1"},
{L"Defiler","DEFILER","sssa_dlc_biker","defiler"},
{L"Diablous 2","DIABLOUS2","lsc_dlc_import_export","diablous2"},
{L"Diablous","DIABLOUS","",""},
{L"Double","DOUBLE","sssa_default","double"},
{L"Enduro","ENDURO","sssa_dlc_heist","enduro"},
{L"Esskey","ESSKEY","sssa_dlc_biker","esskey"},
{L"FCR Custom","FCR2","lsc_dlc_import_export","fcr2_b"},
{L"FCR","FCR","lsc_dlc_import_export","fcr2_a"},
{L"Faggio Custom","FAGGIO3","sssa_dlc_biker","faggio3"},
{L"Faggio","FAGGIO","sssa_default","faggio"},
{L"Faggion","FAGGIO2","sssa_dlc_biker","faggion"},
{L"Gargoyle","GARGOYLE","sssa_dlc_stunt","gargoyle"},
{L"Hakuchou 2","HAKUCHOU2","lgm_dlc_biker","hakuchou2"},
{L"Hakuchou","HAKUCHOU","sssa_dlc_lts_creator","hakuchou"},
{L"Hexer","HEXER","sssa_default","hexer"},
{L"Innovation","INNOVATION","sssa_dlc_lts_creator","innovation"},
{L"Lectro","LECTRO","lgm_dlc_heist","lectro"},
{L"Manchez","MANCHEZ","sssa_dlc_biker","manchez"},
{L"Nemesis","NEMESIS","sssa_dlc_heist","nemesis"},
{L"Nightblade","NIGHTBLADE","sssa_dlc_biker","nightblade"},
{L"Oppressor 2","Oppressor2","candc_battle","oppressor2"},
{L"Oppressor","Oppressor","candc_gunrunning","oppressor"},
{L"PCJ","PCJ","sssa_default","pcj"},
{L"Ratbike","RATBIKE","sssa_dlc_biker","ratbike"},
{L"Rocket","rrocket","lgm_dlc_vinewood","rrocket"},
{L"Ruffian","RUFFIAN","sssa_default","ruffian"},
{L"Sanchez 2","SANCHEZ2","sssa_default","sanchez2"},
{L"Sanchez","SANCHEZ","sssa_default","sanchez"},
{L"Sanctus","SANCTUS","sssa_dlc_biker","sanctus"},
{L"Shotaro","SHOTARO","lgm_dlc_biker","shotaro"},
{L"Sovereign","SOVEREIGN","",""},
{L"Stryder","stryder","lgm_dlc_casinoheist","stryder"},
{L"Thrust","THRUST","lgm_dlc_business2","thrust"},
{L"Vader","VADER","sssa_default","vader"},
{L"Vindicator","VINDICATOR","lgm_dlc_luxe","vindicator"},
{L"Vortex","VORTEX","sssa_dlc_biker","vortex"},
{L"Wolfsbane","WOLFSBANE","sssa_dlc_biker","wolfsbane"},
{L"Zombie 2","ZOMBIEB","sssa_dlc_biker","zombieb"},
{L"Zombie","ZOMBIEA","sssa_dlc_biker","zombiea"}
};
static std::vector<VehiclePreview> Military{
{L"APC","apc","candc_gunrunning","apc"},
{L"Anti-Aircraft Trailer","Trailersmall2","candc_gunrunning","trsmall2"},
{L"Barracks Truck 3","Barracks3","",""},
{L"Barracks Truck","Barracks","candc_default","barracks"},
{L"Barrage","barrage","candc_xmas2017","barrage_b"},
{L"Chernobog","chernobog","candc_xmas2017","chernobog_b"},
{L"Crusader (Army Mesa)","Crusader","candc_default","crusader"},
{L"Half-Track","halftrack","candc_gunrunning","halftrack"},
{L"Khanjali","khanjali","candc_xmas2017","khanjali_b"},
{L"Rhino Tank","Rhino","candc_default","rhino"},
{L"Scarab 2","SCARAB2","mba_vehicles","scarab2"},
{L"Scarab 3","SCARAB3","mba_vehicles","scarab3"},
{L"Scarab","SCARAB","mba_vehicles","scarab1"},
{L"Thruster","thruster","candc_xmas2017","thruster_b"},
{L"Truck Cab","Barracks2","",""}
};
static std::vector<VehiclePreview> Emergency{
{L"Ambulance","Ambulance","",""},
{L"Buffalo (FIB)","Fbi","",""},
{L"Firetruck","Firetruk","",""},
{L"Granger (FIB)","Fbi2","",""},
{L"Lifeguard","Lguard","",""},
{L"Park Ranger","Pranger","",""},
{L"Police 3","Police3","",""},
{L"Police Bike","Policeb","",""},
{L"Police Buffalo","Police2","",""},
{L"Police Cruiser","Police","",""},
{L"Police Rancher (Snow)","Policeold1","",""},
{L"Police Roadcruiser","Policeold2","",""},
{L"Police Riot Van","Riot","",""},
{L"Police Transporter","Policet","",""},
{L"Prison Bus","Pbus","candc_default","pbus"},
{L"Rcv","riot2","candc_xmas2017","riot2_b"},
{L"Sheriff Cruiser","Sheriff","",""},
{L"Sheriff SUV","Sheriff2","",""},
{L"Unmarked Police Cruiser","Police4","",""}
};
static std::vector<VehiclePreview> Service{
{L"Airport Bus","Airbus","candc_default","airbus"},
{L"Brickade","Brickade","candc_executive1","brickade"},
{L"City Bus","Bus","candc_default","bus"},
{L"Coach","Coach","candc_default","coach"},
{L"Dune","Rallytruck","sssa_dlc_stunt","rallytruck"},
{L"Party Bus","Pbus2","sssa_dlc_battle","pbus2"},
{L"Rental Shuttle Bus","Rentalbus","candc_default","rentbus"},
{L"Stanier Taxi","Taxi","",""},
{L"Tourbus","Tourbus","",""},
{L"Trashmaster (Rusty)","Trash2","",""},
{L"Trashmaster","Trash","",""},
{L"Wastelander","Wastelander","candc_importexport","wastlndr"},
};
static std::vector<VehiclePreview> Sedans{
{L"Asea (snow)","Asea2","",""},
{L"Asea","Asea","sssa_dlc_business","asea"},
{L"Asterope","Asterope","sssa_dlc_business","astrope"},
{L"Cognoscenti 55","Cog55","lgm_dlc_apartments","cognosc"},
{L"Cognoscenti 55 (Armored)","Cog552","",""},
{L"Declasse Premier","Premier","sssa_dlc_business","premier"},
{L"Emperor (Rusty)","Emperor2","",""},
{L"Emperor (Snow)","Emperor3","",""},
{L"Emperor","Emperor","",""},
{L"Enus Diamond","Superd","sssa_default","superd"},
{L"Fugitive","Fugitive","sssa_default","fugitive"},
{L"Glendale","Glendale","sssa_dlc_hipster","glendale"},
{L"Karin Intruder","Intruder","sssa_dlc_business","intruder"},
{L"Limo (Armored)","Limo2","",""},
{L"Limo","Stretch","sssa_default","stretch"},
{L"Primo (Custom)","Primo2","",""},
{L"Primo","Primo","sssa_dlc_hipster","primo"},
{L"Regina","Regina","sssa_dlc_hipster","regina"},
{L"Romero Hearse","Romero","sssa_dlc_battle","Romero"},
{L"Schafter (Armored)","Schafter5","lgm_dlc_apartments","schafter3"},
{L"Schafter (CEO)","Schafter6","lgm_dlc_apartments","schafter4"},
{L"Schafter","Schafter2","sssa_dlc_heist","schafter2"},
{L"Stafford","Stafford","lgm_dlc_battle","stafford"},
{L"Stanier","Stanier","sssa_dlc_business","stanier"},
{L"Stratum","Stratum","sssa_dlc_business","stratum"},
{L"Surge","Surge","sssa_dlc_heist","surge"},
{L"Tailgater","Tailgater","sssa_dlc_hipster","tailgater"},
{L"Vulcan Ingot","Ingot","sssa_dlc_business","ingot"},
{L"Vulcar Warrener","Warrener","sssa_dlc_hipster","warrener"},
{L"Washington","Washington","sssa_dlc_business","washingt"}
};
static std::vector<VehiclePreview> Industrial{
{L"Bulldozer","Bulldozer","",""},
{L"Cutter","Cutter","",""},
{L"Dock Handler","Handler","",""},
{L"Dump","Dump","candc_default","dump"},
{L"Flatbed","Flatbed","",""},
{L"Guardian","Guardian","sssa_dlc_heist","guardian"},
{L"Mixer (Support Wheel)","Mixer2","",""},
{L"Mixer","Mixer","",""},
{L"Rubble","Rubble","",""},
{L"Tiptruck (empty)","Tiptruck","",""},
{L"Tiptruck","Tiptruck2","",""}
};
static std::vector<VehiclePreview> Compacts{
{L"Asbo","asbo","sssa_dlc_casinoheist","asbo"},
{L"Blista","Blista","",""},
{L"Dilettante (Patrol)","Dilettante2","",""},
{L"Dilettante","Dilettante","sssa_default","dilettan"},
{L"Grotti Brioso (R/A)","Brioso","sssa_dlc_stunt","brioso"},
{L"Issi 3","issi3","sssa_dlc_assault","issi3"},
{L"Issi 4","ISSI4","mba_vehicles","issi3_c_1"},
{L"Issi 5","ISSI5","mba_vehicles","issi3_c_2"},
{L"Issi 6","ISSI6","mba_vehicles","issi3_c_3"},
{L"Kanjo","kanjo","sssa_dlc_casinoheist","kanjo"},
{L"Panto","Panto","sssa_dlc_hipster","panto"},
{L"Prairie","Prairie","sssa_dlc_battle","prairie"},
{L"Rhapsody","Rhapsody","sssa_dlc_hipster","rhapsody"},
{L"Weeny Issi","Issi2","sssa_default","issi2"}
};
static std::vector<VehiclePreview>  Commercial{
{L"Benson","Benson","",""},
{L"Cerberus 2","CERBERUS2","mba_vehicles","cerberus2"},
{L"Cerberus 3","CERBERUS3","mba_vehicles","cerberus3"},
{L"Cerberus","CERBERUS","mba_vehicles","cerberus1"},
{L"HVY Biff","Biff","",""},
{L"Hauler","Hauler","",""},
{L"Hauler2","Hauler2","candc_truck","cab_1"},
{L"MTL Packer","Packer","",""},
{L"Mule 2","Mule2","",""},
{L"Mule 3","Mule3","candc_default","mule3"},
{L"Mule 4","Mule4","candc_battle","mule4"},
{L"Mule","Mule","candc_default","mule"},
{L"Phantom Custom","phantom3","candc_truck","cab_0"},
{L"Phantom Wedge","Phantom2","candc_importexport","phantom2"},
{L"Phantom","Phantom","",""},
{L"Pounder 2","Pounder2","candc_battle","pounder2"},
{L"Pounder","Pounder","",""},
{L"Stockade (Snow)","Stockade3","",""},
{L"Stockade","Stockade","",""},
{L"Terbyte","Terbyte","",""}
};
static std::vector<VehiclePreview> Planes{
{L"Alphaz1","alphaz1","elt_dlc_smuggler","alphaz1"},
{L"Avenger","avenger","candc_chopper","banner_5"},
{L"Avenger2","avenger2","candc_chopper","banner_4"},
{L"Besra","Besra","elt_dlc_pilot","besra"},
{L"Blimp (Xero)","Blimp2","",""},
{L"Blimp (atomic)","Blimp","",""},
{L"Blimp 3","blimp3","elt_dlc_battle","blimp3"},
{L"Bombushka","Bombushka","candc_smuggler","bombushka"},
{L"Cargoplane","Cargoplane","",""},
{L"Cuban 800","Cuban800","elt_default","cuban800"},
{L"Dodo","Dodo","elt_default","dodo"},
{L"Duster (Rusty)","Duster","elt_default","duster"},
{L"Howard","Howard","elt_dlc_smuggler","howard"},
{L"Hydra","Hydra","candc_default","hydra"},
{L"Jet","Jet","",""},
{L"Luxor (Gold)","Luxor2","elt_dlc_executive1","luxor2"},
{L"Luxor","Luxor","elt_default","luxor"},
{L"Mammatus","Mammatus","elt_default","mammatus"},
{L"Microlight","Microlight","elt_dlc_smuggler","microlight"},
{L"Miljet","Miljet","elt_dlc_pilot","miljet"},
{L"Mogul","Mogul","candc_smuggler","mogul"},
{L"Molotok","Molotok","candc_smuggler","molotok_b"},
{L"Nimbus","Nimbus","elt_dlc_executive1","nimbus"},
{L"Nokota","Nokota","candc_smuggler","nokota"},
{L"P-996 Lazer","Lazer","candc_smuggler","lazer"},
{L"Pyro","Pyro","candc_smuggler","pyro"},
{L"Rogue","Rogue","candc_smuggler","rogue"},
{L"Seabreeze","Seabreeze","elt_dlc_smuggler","seabreeze"},
{L"Shamal","Shamal","elt_default","shamal"},
{L"Starling","starling","candc_smuggler","starling"},
{L"Strikeforce","Strikeforce","candc_battle","strikeforce"},
{L"Stunt Plane","Stunt","elt_default","stunt"},
{L"Titan","Titan","elt_default","titan"},
{L"Tula","tula","candc_smuggler","tula"},
{L"Velum (Heist)","Velum2","elt_default","velum2"},
{L"Velum","Velum","elt_default","velum"},
{L"Vestra","Vestra","",""},
{L"Volatol","volatol","candc_xmas2017","volatol_b"}
};
static std::vector<VehiclePreview> Utility{
{L"Airport Tug","Airtug","",""},
{L"Army Flatbed Trailer (Empty)","Armytrailer","",""},
{L"Army Flatbed Trailer (With Drill)","Armytrailer2","",""},
{L"Army Fuel Tanker","Armytanker","",""},
{L"Boat Trailer (With Boat)","Tr3","",""},
{L"Boat Trailer","Boattrailer","",""},
{L"Caddy (Golf)","Caddy","",""},
{L"Caddy 2","Caddy2","foreclosures_bunker","transportation_2"},
{L"Caddy 3","Caddy3","foreclosures_bunker","transportation_1"},
{L"Car Transport Trailer (Empty)","Tr2","",""},
{L"Car Transport Trailer","Tr4","",""},
{L"Commercial Trailers 1","Trailers2","",""},
{L"Commercial Trailers 2","Trailers3","",""},
{L"Commercial Trailers 3","Trailers4","",""},
{L"Container Trailer","Docktrailer","",""},
{L"Dock Tug","Docktug","",""},
{L"Fame or Shame Trailer","Tvtrailer","",""},
{L"Fieldmaster Tractor (Snow)","Tractor3","",""},
{L"Fieldmaster Tractor","Tractor2","",""},
{L"Flatbed Trailer 1","Freighttrailer","",""},
{L"Flatbed Trailer 2","Trflat","",""},
{L"Fork Lift","Forklift","",""},
{L"Grain Trailer","Graintrailer","",""},
{L"Hay Bale Trailer","Baletrailer","",""},
{L"Logging Trailer","Trailerlogs","",""},
{L"Meth Lab Trailer","Proptrailer","",""},
{L"Mobile Operations Center","trailerlarge","candc_truck","banner_2"},
{L"Petrol Tanker Trailer (Plain)","Tanker2","",""},
{L"Petrol Tanker Trailer (RON)","Tanker","",""},
{L"Pickup Utility Truck","Utillitruck3","",""},
{L"Plain Trailer","Trailers","",""},
{L"Plumbing Utility Truck","Utillitruck2","",""},
{L"Rake Trailer","Raketrailer","",""},
{L"Ripley (Airport Tug)","Ripley","",""},
{L"Scrap Truck","Scrap","",""},
{L"Small Trailer","Trailersmall","",""},
{L"Stanley Lawn Mower","Mower","",""},
{L"Telephone Utility Truck","Utillitruck","",""},
{L"Tow Truck (Big)","Towtruck","",""},
{L"Tow Truck","Towtruck2","",""},
{L"Tractor","Tractor","",""},
{L"Vapid Sadler (Snow)","Sadler2","",""},
{L"Vapid Sadler","Sadler","sssa_default","sadler"},
};
static std::vector<VehiclePreview> Helicopters{
{L"Akula","akula","candc_xmas2017","akula_b"},
{L"Annihilator","Annihilator","elt_default","annihl"},
{L"Buzzard","Buzzard","candc_default","buzzard"},
{L"Buzzard(Unarmed)","Buzzard2","",""},
{L"Cargobob (Closed doors)","Cargobob4","",""},
{L"Cargobob (Jetsam)","Cargobob2","",""},
{L"Cargobob (trevor)","Cargobob3","",""},
{L"Cargobob","Cargobob","candc_default","cargobob"},
{L"Frogger","Frogger","elt_default","frogger"},
{L"Frogger(FIB)","Frogger2","",""},
{L"Havok","havok","elt_dlc_smuggler","havok"},
{L"Hunter","hunter","candc_smuggler","hunter"},
{L"Maverick","Maverick","elt_default","maverick"},
{L"Police Maverick","Polmav","",""},
{L"Savage","Savage","candc_default","savage"},
{L"Sea Sparrow","SEASPARROW","elt_dlc_assault","sparrow"},
{L"Skylift","Skylift","",""},
{L"Supervolito (CEO)","Supervolito2","",""},
{L"Supervolito","Supervolito","",""},
{L"Swift (Gold)","Swift2","elt_dlc_executive1","swift2"},
{L"Swift","Swift","elt_dlc_pilot","swift"},
{L"Valkyrie (Unarmed)","Valkyrie2","",""},
{L"Valkyrie","Valkyrie","candc_default","valkyrie"},
{L"Volatus","Volatus","elt_dlc_executive1","volatus"},
};
static std::vector<VehiclePreview> Vans{
{L"BF Surfer (Rusty)","Surfer2","",""},
{L"BF Surfer","Surfer","sssa_dlc_hipster","surfer"},
{L"Bison (Backrack)","Bison2","",""},
{L"Bison (Construction)","Bison3","",""},
{L"Bison","Bison","sssa_default","bison"},
{L"Bobcat XL","Bobcatxl","sssa_dlc_business","bobcatxl"},
{L"Boxville (Armed)","Boxville5","candc_importexport","boxville5"},
{L"Boxville (Go Postal)","Boxville2","",""},
{L"Boxville (Humane)","Boxville3","",""},
{L"Boxville (Post OP)","Boxville4","candc_default","boxville4"},
{L"Boxville","Boxville","",""},
{L"Brute Pony (Business)","Pony","",""},
{L"Brute Pony (Cannibus Shop)","Pony2","",""},
{L"Burrito (Bug Stars)","Burrito2","",""},
{L"Burrito (Construction)","Burrito4","",""},
{L"Burrito (Gang 2)","Gburrito2","sssa_dlc_heist","gburrito2"},
{L"Burrito (Gang)","Gburrito","",""},
{L"Burrito (Snow)","Burrito5","",""},
{L"Burrito (clear)","Burrito3","",""},
{L"Burrito","Burrito","",""},
{L"Camper","Camper","",""},
{L"Journey","Journey","candc_default","journey"},
{L"Minivan (Custom)","Minivan2","lsc_lowrider2","minivan2_b"},
{L"Minivan","Minivan","sssa_dlc_business","minivan"},
{L"Paradise","Paradise","sssa_default","paradise"},
{L"Rumpo (Armored)","Rumpo3","sssa_dlc_executive_1","rumpo3_b"},
{L"Rumpo (Deludamol)","Rumpo2","",""},
{L"Rumpo","Rumpo","sssa_dlc_heist","rumpo"},
{L"Speedo 4","Speedo4","",""},
{L"Speedo 2 (Clown)","Speedo2","",""},
{L"Speedo","Speedo","",""},
{L"Taco Van","Taco","",""},
{L"Youga (classic)","Youga2","sssa_dlc_biker","youga2"},
{L"Youga","Youga","sssa_dlc_hipster","youga"}
};
static std::vector<VehiclePreview> Boats{
{L"Dinghy","Dinghy","",""},
{L"Dinghy (Additional light)","Dinghy2","",""},
{L"Dinghy (Heist)","Dinghy3","dock_default","dinghy3"},
{L"Dinghy","Dinghy4","",""},
{L"Jetmax","Jetmax","dock_default","jetmax"},
{L"Marquis","Marquis","dock_default","marquis"},
{L"Predator (Police)","Predator","",""},
{L"Seashark","Seashark","dock_default","seashark"},
{L"Seashark (Lifeguard)","Seashark2","",""},
{L"Seashark (Charged)","Seashark3","",""},
{L"Speeder","Speeder","dock_default","speeder"},
{L"Speeder (Colored)","Speeder2","",""},
{L"Squalo","Squalo","dock_default","squalo"},
{L"Submarine","Submersible","",""},
{L"Submarine (Kraken)","Submersible2","dock_default","sub2"},
{L"Suntrap","Suntrap","dock_default","suntrap"},
{L"Toro","Toro","dock_default","toro"},
{L"Toro (Colored)","Toro2","",""},
{L"Tropic","Tropic","dock_default","tropic"},
{L"Tropic (handrail)","Tropic2","",""},
{L"Tug","Tug","",""}
};
static std::vector<VehiclePreview> Cycles{
{L"Bmx","Bmx","pandm_default","bmx"},
{L"Cruiser","Cruiser","pandm_default","cruiser"},
{L"Endurex","Tribike2","pandm_default","tribike2"},
{L"Fixter","Fixter","",""},
{L"Scorcher","Scorcher","pandm_default","scorcher"},
{L"Tri-Cycle","Tribike3","pandm_default","tribike3"},
{L"Whippet","Tribike","pandm_default","tribike"}
};
static std::vector<VehiclePreview> Trains{
{L"Cable Car (Mt. Chilliad)","Cablecar","",""},
{L"Container Cars 2","Freightcont1","",""},
{L"Container Cars 2","Freightcont2","",""},
{L"Flatbed Car","Freightcar","",""},
{L"Freight Train Cab","Freight","",""},
{L"Grain Car","Freightgrain","",""},
{L"Metro Train (Half)","Metrotrain","",""},
{L"Oil Tanker Car","Tankercar","",""}
};
static std::vector<VehiclePreview> Trailer{
{L"Army Fuel Tanker", "Armytanker", "", "" },
{L"Army Flatbed Trailer (Empty)", "Armytrailer", "", "" },
{L"Army Flatbed Trailer (With Drill)", "Armytrailer2", "", "" },
{L"Hay Bale Trailer", "Baletrailer", "", "" },
{L"Boat Trailer", "Boattrailer", "", "" },
{L"Container Trailer", "Docktrailer", "", "" },
{L"Flatbed Trailer 1", "Freighttrailer", "", "" },
{L"Grain Trailer", "Graintrailer", "", "" },
{L"Meth Lab Trailer", "Proptrailer", "", "" },
{L"Rake Trailer", "Raketrailer", "", "" },
{L"Petrol Tanker Trailer (RON)", "Tanker", "", "" },
{L"Petrol Tanker Trailer (Plain)", "Tanker2", "", "" },
{L"Car Transport Trailer (Empty)", "Tr2", "", "" },
{L"Boat Trailer (With Boat)", "Tr3", "", "" },
{L"Car Transport Trailer", "Tr4", "", "" },
{L"Logging Trailer", "Trailerlogs", "", "" },
{L"Plain Trailer", "Trailers", "", "" },
{L"Commercial Trailers 1", "Trailers2", "", "" },
{L"Commercial Trailers 2", "Trailers3", "", "" },
{L"Commercial Trailers 3", "Trailers4", "", "" },
{L"Small Trailer", "Trailersmall", "", "" },
{L"Mobile Operations Center", "trailerlarge", "", "" },
{L"Flatbed Trailer 2", "Trflat", "", "" },
{L"Fame or Shame Trailer", "Tvtrailer", "", "" }
};
static std::vector<VehiclePreview> SUV{
{L"Baller (CEO)","Baller6","",""},
{L"Baller 2","Baller2","sssa_default","baller2"},
{L"Baller LE (Armored)","Baller5","",""},
{L"Baller LE LWB","Baller4","lgm_dlc_apartments","baller4"},
{L"Baller LE","Baller3","lgm_dlc_apartments","baller3"},
{L"Baller","Baller","",""},
{L"BeeJay XL","Bjxl","sssa_dlc_battle","bjxl"},
{L"Canis Seminole","Seminole","sssa_dlc_heist","seminole"},
{L"Cavalcade Mk2","CAVALCADE2","sssa_dlc_business","cavcade2"},
{L"Cavalcade","CAVALCADE","sssa_default","cavcade"},
{L"Contender","Contender","sssa_dlc_stunt","contender"},
{L"Dubsta (Flat Black)","Dubsta2","",""},
{L"Dubsta","Dubsta","",""},
{L"Emperor Habanero","Habanero","sssa_dlc_battle","habanero"},
{L"Enus Huntley S","Huntley","lgm_dlc_business2","huntley"},
{L"Fathom FQ 2","fq2","sssa_dlc_battle","fq2"},
{L"Granger","Granger","sssa_dlc_business","granger"},
{L"Gresley","Gresley","sssa_dlc_heist","gresley"},
{L"Landstalker","Landstalker","sssa_dlc_heist","landstalker"},
{L"Mammoth Patriot","Patriot","sssa_dlc_battle","patriot"},
{L"Mesa (Snow)","Mesa2","",""},
{L"Mesa","Mesa","candc_default","mesa"},
{L"Novak","novak","lgm_dlc_vinewood","novak"},
{L"Patriot 2","Patriot2","sssa_dlc_battle","patriot2"},
{L"Radius","Radi","sssa_dlc_business","radi"},
{L"Rebla","rebla","lgm_dlc_casinoheist","rebla"},
{L"Rocoto","Rocoto","sssa_default","rocoto"},
{L"Serrano","Serrano","sssa_dlc_battle","serrano"},
{L"Toros","TOROS","lgm_dlc_arena","toros"},
{L"Xls (Armored)","Xls2","",""},
{L"Xls","Xls","lgm_dlc_executive1","xls"}
};
static std::vector<std::pair<std::wstring, std::vector<VehiclePreview>>> vehiclePreview{
	{L"超跑 >>",Super},
	{L"跑车 >>",Sports},
	{L"经典跑车 >>",SportsClassics},
	{L"轿跑 >>",Coupes},
	{L"肌肉车 >>",Muscle},
	{L"越野车 >>",Offroad},
	{L"摩托车 >>",Motorcycles},
	{L"军用车辆 >>",Military},
	{L"应急车辆 >>",Emergency},
	{L"服务车辆 >>",Service},
	{L"轿车 >>",Sedans},
	{L"工业车辆 >>",Industrial},
	{L"小型车 >>",Compacts},
	{L"商用车 >>",Commercial},
	{L"飞机 >>",Planes},
	{L"多用途车 >>",Utility},
	{L"直升飞机 >>",Helicopters},
	{L"厢式货车 >>",Vans},
	{L"船 >>",Boats},
	{L"自行车 >>",Cycles},
	{L"火车 >>",Trains},
	{L"拖车 >>",Trailer},
	{L"SUV >>",SUV},
};


static unsigned int joaat(std::string input)
{
	unsigned int num1 = 0U;
	for (char c : input)
	{
		unsigned int num2 = num1 + (unsigned int)tolower(c);
		unsigned int num3 = num2 + (num2 << 10);
		num1 = num3 ^ num3 >> 6;
	}
	unsigned int num4 = num1 + (num1 << 3);
	unsigned int num5 = num4 ^ num4 >> 11;
	return num5 + (num5 << 15);
}