#pragma once
#include<vector>

struct VehiclePreview {
	char* VName;
	char* VCode;
	char* TexDict;
	char* TexName;
};


static std::vector<VehiclePreview> Super{
{"811","Pfister811","lgm_dlc_executive1","pfister811"},
{"Adder","Adder","lgm_default","adder"},
{"Autarch","autarch","lgm_dlc_xmas2017","autarch_b"},
{"Banshee 900R","Banshee2","lsc_jan2016","banshee2"},
{"Bullet","Bullet","lgm_default","bullet"},
{"Cheetah","Cheetah","lgm_default","cheetah"},
{"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{"Cyclone","cyclone","lgm_dlc_smuggler","cyclone"},
{"Deveste","DEVESTE","lgm_dlc_arena","deveste"},
{"ETR1","Sheava","lgm_dlc_stunt","sheava"},
{"Emerus","emerus","lgm_dlc_vinewood","emerus"},
{"Entity 2","entity2","lgm_dlc_assault","entity2"},
{"Entity XF","Entityxf","lgm_default","entityxf"},
{"FMJ","Fmj","lgm_dlc_executive1","fmj"},
{"Furia","furia","lgm_dlc_casinoheist","furia"},
{"GP1","gp1","lgm_dlc_specialraces","gp1"},
{"Infernus","Infernus","sssa_default","infernus"},
{"Itali GTB Custom","italigtb2","lsc_dlc_import_export","italigtb2"},
{"Itali GTB","Italigtb","lsc_dlc_import_export","italigtb"},
{"Krieger","krieger","lgm_dlc_vinewood","krieger"},
{"Nero Custom","Nero2","lsc_dlc_import_export","nero2_b"},
{"Nero","Nero","lsc_dlc_import_export","nero2_a"},
{"Osiris","Osiris","lgm_dlc_luxe","Osiris"},
{"Penetrator","Penetrator","lgm_dlc_importexport","penetrator"},
{"RE-7B","Le7b","lgm_dlc_stunt","le7b"},
{"Reaper","Reaper","lgm_dlc_executive1","reaper"},
{"Rocket Voltic","voltic2","candc_importexport","voltic2"},
{"S80","s80","lgm_dlc_vinewood","s80"},
{"Sc1","sc1","lgm_dlc_xmas2017","sc1_b"},
{"Scramjet","Scramjet","candc_battle","scramjet"},
{"Sultan RS","Sultanrs","lsc_jan2016","sultan2_a"},
{"T20","T20","lgm_dlc_luxe","t20"},
{"Taipan","taipan","lgm_dlc_assault","taipan"},
{"Tempesta","Tempesta","lgm_dlc_importexport","tempesta"},
{"Tezeract","tezeract","lgm_dlc_assault","tezeract"},
{"Thrax","thrax","lgm_dlc_vinewood","thrax"},
{"Turismo R","turismor","lgm_dlc_business","turismor"},
{"Tyrant","TYRANT","lgm_dlc_assault","tyrant"},
{"Tyrus","Tyrus","lgm_dlc_stunt","tyrus"},
{"Vacca","Vacca","lgm_default","vacca"},
{"Vagner","Vagner","lgm_dlc_gunrunning","vagner"},
{"Vigilante","Vigilante","candc_smuggler","vigilante"},
{"Visione","visione","lgm_dlc_smuggler","visione"},
{"Voltic","Voltic","lgm_default","voltic_tless"},
{"X80 Proto","Prototipo","lgm_dlc_executive1","prototipo"},
{"XA21","xa21","lgm_dlc_gunrunning","xa21"},
{"Zentorno","Zentorno","lgm_dlc_business2","zentorno"},
{"Zorrusso","zorrusso","lgm_dlc_vinewood","zorrusso"}
};
static std::vector<VehiclePreview> Sports{
{"Alpha","Alpha","lgm_dlc_business","alpha"},
{"Banshee","Banshee","lgm_dlc_business2","banshee_tless"},
{"Bestia Compact","Blista2","sssa_dlc_mp_to_sp","blista2"},
{"Bestia GTS","Bestiagts","lgm_dlc_executive1","bestiagts"},
{"Blista Compact (Race)","blista3","",""},
{"Buffalo S","Buffalo2","sssa_dlc_hipster","buffalo"},
{"Buffalo Sprunk","Buffalo3","sssa_dlc_mp_to_sp","buffalo3"},
{"Buffalo","Buffalo","sssa_dlc_hipster","buffalo"},
{"Carbonizzare","Carbonizzare","lgm_default","carboniz"},
{"Comet Retro Custom","Comet3","lsc_dlc_import_export","comet3"},
{"Comet","Comet2","sssa_default","comet2"},
{"Comet4","comet4","lgm_dlc_xmas2017","comet4_b"},
{"Comet5","comet5","lgm_dlc_xmas2017","comet5_b"},
{"Coquette","Coquette","lgm_default","coquette"},
{"Drafter","drafter","lgm_dlc_vinewood","drafter"},
{"Drift Tampa","tampa2","sssa_dlc_stunt","tampa2"},
{"Elegy RH8","Elegy2","lgm_default","elegy2"},
{"Elegy Retro Custom","Elegy","lsc_dlc_import_export","elegy"},
{"Feltzer 2","Feltzer2","",""},
{"Formula PR4", "formula", "lgm_dlc_casinoheist", "formula"},
{"Formula2 R88", "formula2", "lgm_dlc_casinoheist", "formula2"},
{"Flash GT","flashgt","lgm_dlc_assault","flashgt"},
{"Furore GT","Furoregt","lgm_dlc_lts_creator","furore"},
{"Fusilade","Fusilade","sssa_dlc_business2","fusilade"},
{"Futo","futo","sssa_dlc_battle","futo"},
{"GB200","gb200","lgm_dlc_assault","gb200"},
{"Hotring","hotring","sssa_dlc_assault","hotring"},
{"Imorgon","imorgon","lgm_dlc_casinoheist","imorgon"},
{"Issi 7","issi7","sssa_dlc_vinewood","issi7"},
{"Italigto","ITALIGTO","lgm_dlc_arena","italigto"},
{"Jester (Race)","jester2","sssa_dlc_christmas_2","jester2"},
{"Jester 3","jester3","lgm_dlc_assault","jester3"},
{"Jester","Jester","lgm_dlc_business","jester"},
{"Jugular","jugular","lgm_dlc_vinewood","jugular"},
{"Khamelion","Khamelion","",""},
{"Komoda","komoda","lgm_dlc_casinoheist","komoda"},
{"Kuruma Armored","kuruma2","sssa_dlc_heist","kuruma2"},
{"Kuruma","kuruma","sssa_dlc_heist","kuruma"},
{"Locust","locust","lgm_dlc_vinewood","locust"},
{"Lynx","lynx","lgm_dlc_stunt","lynx"},
{"Massacro (Race)","Massacro2","sssa_dlc_christmas_2","massacro2"},
{"Massacro","Massacro","lgm_dlc_business2","massacro"},
{"Neo","neo","lgm_dlc_vinewood","neo"},
{"Neon","neon","lgm_dlc_xmas2017","neon_b"},
{"Obey 9F Cabrio","Ninef2","lgm_default","ninef2"},
{"Obey","Ninef","sssa_default","ninef"},
{"Omnis","Omnis","sssa_dlc_stunt","omnis"},
{"Paragon","paragon","lgm_dlc_vinewood","paragon"},
{"Paragon (Armored)","paragon2","lgm_dlc_vinewood","paragon"},
{"Pariah","pariah","lgm_dlc_xmas2017","pariah_b"},
{"Penumbra","Penumbra","sssa_dlc_business2","penumbra"},
{"Raiden","raiden","lgm_dlc_xmas2017","raiden_b"},
{"Rapid GT Cabrio","rapidgt2","lgm_default","rapidgt2"},
{"Rapid GT","Rapidgt","lgm_default","rapidgt"},
{"Raptor","raptor","lgm_dlc_biker","raptor"},
{"Revolter","revolter","lgm_dlc_xmas2017","revolter_b"},
{"Ruston","ruston","lgm_dlc_specialraces","ruston"},
{"Schafter LWB","schafter4","lgm_dlc_apartments","schafter4"},
{"Schafter V12","schafter3","lgm_dlc_apartments","schafter3"},
{"Schlagen","SCHLAGEN","lgm_dlc_arena","schlagen"},
{"Schwarzer","schwarzer","sssa_default","schwarze"},
{"Sentinel Classic","sentinel3","sssa_dlc_xmas2017","sentinel3_b"},
{"Seven 70","Seven70","lgm_dlc_executive1","seven70"},
{"Specter","specter","lsc_dlc_import_export","specter2_a"},
{"Specter2","specter2","lsc_dlc_import_export","specter2_b"},
{"Streiter","streiter","lgm_dlc_xmas2017","streiter_b"},
{"Sugoi","sugoi","sssa_dlc_casinoheist","sugoi"},
{"Sultan","Sultan","lsc_jan2016","sultan2_a"},
{"Sultan2","sultan2","sssa_dlc_casinoheist","sultan2"},
{"Surano","surano","lgm_default","surano_convertable"},
{"Tropos","tropos","sssa_dlc_stunt","tropos"},
{"V-STR","vstr","lgm_dlc_casinoheist","vstr"},
{"Verlierer","Verlierer2","lgm_dlc_apartments","verlier"},
{"Zr380 2","ZR3802","mba_vehicles","zr3802"},
{"Zr380 3","ZR3803","mba_vehicles","zr3803"},
{"Zr380","ZR380","mba_vehicles","zr3801"}
};
static std::vector<VehiclePreview> SportsClassics{
{"Ardent","Ardent","candc_gunrunning","ardent"},
{"Casco","casco","lgm_dlc_heist","casco"},
{"Cheburek","cheburek","sssa_dlc_assault","cheburek"},
{"Cheetah 2","Cheetah2","lgm_dlc_gunrunning","cheetah2"},
{"Coquette Classic","coquette2","lgm_dlc_pilot","coquette2"},
{"Deluxo","deluxo","candc_xmas2017","deluxo_b"},
{"Dynasty","dynasty","sssa_dlc_vinewood","dynasty"},
{"Fagaloa","fagaloa","sssa_dlc_assault","fagaloa"},
{"Gt500","gt500","lgm_dlc_xmas2017","gt500_b"},
{"Infernus Classic","Infernus2","lgm_dlc_specialraces","infernus2"},
{"JB700","jb700","lgm_default","jb700"},
{"JB700W","jb7002","lgm_default","jb700"},
{"Mamba","mamba","lgm_dlc_apartments","mamba"},
{"Manana","manana","",""},
{"Michelli","michelli","sssa_dlc_assault","michelli"},
{"Monroe","monroe","lgm_default","monroe"},
{"Nebula","nebula","sssa_dlc_vinewood","nebula"},
{"Peyote","Peyote","",""},
{"Pigalle","pigalle","sssa_dlc_hipster","pigalle"},
{"Rapid GT 3","rapidgt3","lgm_dlc_smuggler","rapidgt3"},
{"Retinue 2","retinue2","sssa_dlc_casinoheist","retinue2"},
{"Retinue","Retinue","",""},
{"Retinue","Retinue","sssa_dlc_smuggler","retinue_b"},
{"Roosevelt (Halloween)","btype2","sssa_dlc_halloween","btype2"},
{"Roosevelt Valor","btype3","lgm_dlc_valentines2","roosevelt2"},
{"Roosevelt","btype","lgm_dlc_valentines","roosevelt"},
{"Savestra","savestra","lgm_dlc_xmas2017","savestra_b"},
{"Stinger GT","stingergt","lgm_default","stingerg"},
{"Stinger","stinger","lgm_default","stinger"},
{"Stirling GT","Feltzer3","lgm_dlc_luxe","feltzer3"},
{"Stromberg","stromberg","candc_xmas2017","stromberg_b"},
{"Swinger","Swinger","lgm_dlc_battle","swinger"},
{"Torero","torero","lgm_dlc_gunrunning","torero"},
{"Tornado","Tornado","",""},
{"Tornado 2 Cabrio","Tornado2","",""},
{"Tornado 3(Rusty)","Tornado3","",""},
{"Tornado 4 Cabrio (Rusty)","Tornado4","",""},
{"Tornado 5","Tornado5","lsc_lowrider2","tornado5_a"},
{"Tornado 6 Rat","tornado6","sssa_dlc_biker","tornado6"},
{"Turismo Classic","turismo2","lgm_dlc_specialraces","turismo2"},
{"Viseris","viseris","lgm_dlc_xmas2017","viseris_b"},
{"Z-Type","ztype","lgm_default","ztype"},
{"Z190","z190","lgm_dlc_xmas2017","z190_b"},
{"Zion 3","zion3","sssa_dlc_vinewood","zion3"}
};
static std::vector<VehiclePreview> Coupes{
{"Cognoscenti Cabrio","cogcabrio","lgm_default","cogcabri"},
{"Exemplar","Exemplar","sssa_default","exemplar"},
{"F620","F620","sssa_dlc_business2","f620"},
{"Felon","Felon","sssa_default","felon"},
{"Felon Topless","Felon2","sssa_default","felon2"},
{"Jackal","Jackal","sssa_dlc_heist","jackal"},
{"Oracle","Oracle","sssa_default","oracle"},
{"Oracle 2","oracle2","sssa_dlc_heist","oracle1"},
{"Sentinel XS","Sentinel","sssa_dlc_business2","sentinel"},
{"Sentinel","Sentinel2","sssa_dlc_business2","sentinel"},
{"Windsor","Windsor","lgm_dlc_luxe","windsor"},
{"Windsor Drop","Windsor2","",""},
{"Zion","Zion","sssa_default","zion"},
{"Zion Cabrio","Zion2","sssa_default","zion2"}
};
static std::vector<VehiclePreview> Muscle{
{"Blade","Blade","sssa_dlc_hipster","blade"},
{"Broken Ruiner","ruiner3","",""},
{"Buccaneer Custom","Buccaneer2","lsc_default","buccaneer2_b"},
{"Buccaneer","Buccaneer","lsc_default","buccaneer2_a"},
{"Chino 2","Chino2","lsc_default","chino2_a"},
{"Chino","Chino","lgm_dlc_luxe","chino"},
{"Clique","CLIQUE","lgm_dlc_arena","clique"},
{"Coquette Classic","coquette3","lgm_dlc_luxe","coquette3"},
{"Deviant","DEVIANT","lgm_dlc_arena","deviant"},
{"Dominator 3","dominator3","sssa_dlc_assault","dominator3"},
{"Dominator 4","DOMINATOR4","mba_vehicles","dominato_c_1"},
{"Dominator 5","DOMINATOR5","mba_vehicles","dominato_c_2"},
{"Dominator 6","DOMINATOR6","mba_vehicles","dominato_c_3"},
{"Dominator","Dominator","sssa_dlc_business2","dominato"},
{"Duke O' Death","Dukes2","candc_default","dukes"},
{"Dukes","Dukes","sssa_dlc_mp_to_sp","dukes"},
{"Ellie","ellie","sssa_dlc_assault","ellie"},
{"Faction Custom 2","Faction3","lsc_lowrider2","faction3_b"},
{"Faction Custom","Faction2","lsc_lowrider2","faction3_a"},
{"Faction","Faction","lsc_default","faction2_a"},
{"Gauntlet (Race)","Gauntlet2","sssa_dlc_mp_to_sp","gauntlet2"},
{"Gauntlet 3","gauntlet3","sssa_dlc_vinewood","gauntlet3"},
{"Gauntlet 4","gauntlet4","sssa_dlc_vinewood","gauntlet4"},
{"Gauntlet","Gauntlet","sssa_default","gauntlet"},
{"Hermes","hermes","sssa_dlc_xmas2017","hermes_b"},
{"Hotknife","Hotknife","lgm_default","hotknife"},
{"Hustler","hustler","lgm_dlc_xmas2017","hustler_b"},
{"Impaler","IMPALER","mba_vehicles","impaler"},
{"Impaler","impaler","sssa_dlc_vinewood","impaler"},
{"Impaler2","IMPALER2","mba_vehicles","impaler_c_1"},
{"Impaler3","IMPALER3","mba_vehicles","impaler_c_2"},
{"Impaler4","IMPALER4","mba_vehicles","impaler_c_3"},
{"Imperator 2","IMPERATOR2","mba_vehicles","imperator2"},
{"Imperator 3","IMPERATOR3","mba_vehicles","imperator3"},
{"Imperator","IMPERATOR","mba_vehicles","imperator1"},
{"Lurcher","lurcher","sssa_dlc_halloween","lurcher"},
{"Moonbeam Custom","Moonbeam2","lsc_default","moonbeam2"},
{"Moonbeam","Moonbeam","",""},
{"Nightshade","nightshade","lgm_dlc_apartments","niteshad"},
{"Peyote 2","peyote2","sssa_dlc_vinewood","peyote2"},
{"Phoenix","phoenix","",""},
{"Picador","picador","sssa_dlc_hipster","picador"},
{"Pisswasser Dominator","Dominator2","sssa_dlc_mp_to_sp","dominator2"},
{"Ratloader (Rusty)","ratloader","sssa_dlc_valentines","rloader"},
{"Ratloader","ratloader2","sssa_dlc_christmas_2","rloader2"},
{"Ruiner 2000","ruiner2","candc_importexport","ruiner2"},
{"Ruiner","ruiner","sssa_dlc_battle","ruiner"},
{"Sabre Turbo","Sabregt","",""},
{"Sabre","Sabregt2","lsc_lowrider2","sabregt2_a"},
{"Slamvan (Lost MC)","Slamvan2","",""},
{"Slamvan 3","Slamvan3","lsc_lowrider2","slamvan3_b"},
{"Slamvan 4","SLAMVAN4","mba_vehicles","slamvan_c_1"},
{"Slamvan 5","SLAMVAN5","mba_vehicles","slamvan_c_2"},
{"Slamvan 6","SLAMVAN6","mba_vehicles","slamvan_c_3"},
{"Slamvan","Slamvan","sssa_dlc_christmas_2","slamvan"},
{"Stalion (Race)","stalion2","sssa_dlc_mp_to_sp","stalion2"},
{"Stalion","Stalion","sssa_dlc_mp_to_sp","stallion"},
{"Tampa 3","tampa3","candc_gunrunning","tampa3"},
{"Tampa","Tampa","sssa_dlc_christmas_3","tampa"},
{"Tulip","TULIP","sssa_dlc_arena","tulip"},
{"Vamos","VAMOS","sssa_dlc_arena","vamos"},
{"Vigero","Vigero","sssa_default","vigero"},
{"Virgo Classic","Virgo2","lsc_lowrider2","virgo2_a"},
{"Virgo Custom","Virgo3","lsc_lowrider2","virgo2_b"},
{"Virgo","Virgo","lgm_dlc_luxe","virgo"},
{"Voodoo Custom","Voodoo2","lsc_default","voodoo_b"},
{"Voodoo","Voodoo","lsc_default","voodoo_a"},
{"Yosemite","yosemite","sssa_dlc_xmas2017","yosemite_b"},
{"Yosemite","yosemite2","sssa_dlc_casinoheist","yosemite2"}
};
static std::vector<VehiclePreview> Offroad{
{"BF Injection","bfinjection","sssa_default","bfinject"},
{"Bifta","Bifta","sssa_default","bifta"},
{"Blazer (Trevor's)","Blazer3","sssa_dlc_hipster","blazer3"},
{"Blazer Aqua","Blazer5","candc_importexport","blazer5"},
{"Blazer lifeguard","Blazer2","",""},
{"Blazer","Blazer","sssa_default","blazer"},
{"Blazer4","Blazer4","sssa_dlc_biker","blazer4"},
{"Bodhi","Bodhi2","sssa_default","bodhi2"},
{"Brawler","Brawler","lgm_dlc_luxe","brawler"},
{"Bruiser 2","BRUISER2","mba_vehicles","bruiser_c_2"},
{"Bruiser 3","BRUISER3","mba_vehicles","bruiser_c_3"},
{"Bruiser","BRUISER","mba_vehicles","bruiser_c_1"},
{"Brutus 2","BRUTUS2","mba_vehicles","brutus2"},
{"Brutus 3","BRUTUS3","mba_vehicles","brutus3"},
{"Brutus","BRUTUS","mba_vehicles","brutus1"},
{"Caracara 2","caracara2","sssa_dlc_vinewood","caracara2"},
{"Caracara","caracara","candc_assault","caracara"},
{"Dubsta 6x6","Dubsta3","candc_default","dubsta3"},
{"Dune (Gunrunning)","Dune3","candc_gunrunning","dune3"},
{"Dune Buggy","Dune","sssa_default","dune"},
{"Duneloader","Dloader","",""},
{"Everon","everon","sssa_dlc_casinoheist","everon"},
{"Freecrawler","Freecrawler","lgm_dlc_battle","freecrawler"},
{"Hellion","hellion","sssa_dlc_vinewood","hellion"},
{"Insurgent 3","Insurgent3","",""},
{"Insurgent 3","Insurgent3","ua_generic","ua_unlock_11"},
{"Insurgent Pick-Up","Insurgent","candc_default","insurgent"},
{"Insurgent","Insurgent2","candc_default","insurgent"},
{"Kalahari","Kalahari","sssa_default","kalahari"},
{"Kamacho","kamacho","sssa_dlc_xmas2017","kamacho_b"},
{"Marshall","marshall","candc_default","marshall"},
{"Menacer","Menacer","candc_battle","menacer"},
{"Mesa","Mesa3","candc_default","mesa3"},
{"Monster 3","MONSTER3","mba_vehicles","monster_c_1"},
{"Monster 4","MONSTER4","mba_vehicles","monster_c_2"},
{"Monster 5","MONSTER5","mba_vehicles","monster_c_3"},
{"Night Shark","nightshark","candc_gunrunning","nightshark"},
{"Outlaw","outlaw","sssa_dlc_casinoheist","outlaw"},
{"Ramp Buggy (Roof)","Dune4","",""},
{"Ramp Buggy","Dune5","candc_importexport","dune5"},
{"Rancher XL 2","Rancherxl2","",""},
{"Rancher XL","Rancherxl","sssa_dlc_business","rancherx"},
{"Rcbandito","RCBANDITO","sssa_dlc_arena","rcbandito"},
{"Rebel (Rusty)","Rebel2","sssa_dlc_hipster","rebel2"},
{"Rebel","Rebel","sssa_default","rebel"},
{"Riata","riata","sssa_dlc_xmas2017","riata_b"},
{"Sandking XL","Sandking","sssa_default","sandking_b"},
{"Sandking","Sandking2","sssa_default","sandkin_2b"},
{"Space Docker","Dune2","",""},
{"Technical 3","Technical3","",""},
{"Technical Aqua","Technical2","candc_importexport","technical2"},
{"Technical Custom","Technical3","ua_generic","ua_unlock_15"},
{"Technical","Technical","candc_default","technical"},
{"The Liberator","monster","candc_default","monster"},
{"Trophy Truck 2","TrophyTruck2","sssa_dlc_stunt","trophy2"},
{"Trophy Truck","TrophyTruck","sssa_dlc_stunt","trophy"},
{"Vagrant","vagrant","sssa_dlc_casinoheist","vagrant"},
{"Zhaba","Zhaba","",""},

};
static std::vector<VehiclePreview> Motorcycles{
{"Akuma","Akuma","sssa_default","akuma"},
{"Avarus","Avarus","sssa_dlc_biker","avarus"},
{"BF400","BF400","sssa_dlc_stunt","bf400"},
{"Bagger","Bagger","sssa_dlc_biker","bagger"},
{"Bati 801R","BATI2","sssa_default","bati2"},
{"Bati","BATI","sssa_default","bati"},
{"Carbon RS","CARBONRS","lgm_default","carbon"},
{"Chimera","CHIMERA","sssa_dlc_biker","chimera"},
{"Cliffhanger","CLIFFHANGER","sssa_dlc_stunt","cliffhanger"},
{"Daemon 2","DAEMON2","sssa_dlc_biker","daemon2"},
{"Daemon","DAEMON","",""},
{"Deathbike 2","DEATHBIKE2","mba_vehicles","deathbike_c_2"},
{"Deathbike 3","DEATHBIKE3","mba_vehicles","deathbike_c_3"},
{"Deathbike","DEATHBIKE","mba_vehicles","deathbike_c_1"},
{"Defiler","DEFILER","sssa_dlc_biker","defiler"},
{"Diablous 2","DIABLOUS2","lsc_dlc_import_export","diablous2"},
{"Diablous","DIABLOUS","",""},
{"Double","DOUBLE","sssa_default","double"},
{"Enduro","ENDURO","sssa_dlc_heist","enduro"},
{"Esskey","ESSKEY","sssa_dlc_biker","esskey"},
{"FCR Custom","FCR2","lsc_dlc_import_export","fcr2_b"},
{"FCR","FCR","lsc_dlc_import_export","fcr2_a"},
{"Faggio Custom","FAGGIO3","sssa_dlc_biker","faggio3"},
{"Faggio","FAGGIO","sssa_default","faggio"},
{"Faggion","FAGGIO2","sssa_dlc_biker","faggion"},
{"Gargoyle","GARGOYLE","sssa_dlc_stunt","gargoyle"},
{"Hakuchou 2","HAKUCHOU2","lgm_dlc_biker","hakuchou2"},
{"Hakuchou","HAKUCHOU","sssa_dlc_lts_creator","hakuchou"},
{"Hexer","HEXER","sssa_default","hexer"},
{"Innovation","INNOVATION","sssa_dlc_lts_creator","innovation"},
{"Lectro","LECTRO","lgm_dlc_heist","lectro"},
{"Manchez","MANCHEZ","sssa_dlc_biker","manchez"},
{"Nemesis","NEMESIS","sssa_dlc_heist","nemesis"},
{"Nightblade","NIGHTBLADE","sssa_dlc_biker","nightblade"},
{"Oppressor 2","Oppressor2","candc_battle","oppressor2"},
{"Oppressor","Oppressor","candc_gunrunning","oppressor"},
{"PCJ","PCJ","sssa_default","pcj"},
{"Ratbike","RATBIKE","sssa_dlc_biker","ratbike"},
{"Rocket","rrocket","lgm_dlc_vinewood","rrocket"},
{"Ruffian","RUFFIAN","sssa_default","ruffian"},
{"Sanchez 2","SANCHEZ2","sssa_default","sanchez2"},
{"Sanchez","SANCHEZ","sssa_default","sanchez"},
{"Sanctus","SANCTUS","sssa_dlc_biker","sanctus"},
{"Shotaro","SHOTARO","lgm_dlc_biker","shotaro"},
{"Sovereign","SOVEREIGN","",""},
{"Stryder","stryder","lgm_dlc_casinoheist","stryder"},
{"Thrust","THRUST","lgm_dlc_business2","thrust"},
{"Vader","VADER","sssa_default","vader"},
{"Vindicator","VINDICATOR","lgm_dlc_luxe","vindicator"},
{"Vortex","VORTEX","sssa_dlc_biker","vortex"},
{"Wolfsbane","WOLFSBANE","sssa_dlc_biker","wolfsbane"},
{"Zombie 2","ZOMBIEB","sssa_dlc_biker","zombieb"},
{"Zombie","ZOMBIEA","sssa_dlc_biker","zombiea"}
};
static std::vector<VehiclePreview> Military{
{"APC","apc","candc_gunrunning","apc"},
{"Anti-Aircraft Trailer","Trailersmall2","candc_gunrunning","trsmall2"},
{"Barracks Truck 3","Barracks3","",""},
{"Barracks Truck","Barracks","candc_default","barracks"},
{"Barrage","barrage","candc_xmas2017","barrage_b"},
{"Chernobog","chernobog","candc_xmas2017","chernobog_b"},
{"Crusader (Army Mesa)","Crusader","candc_default","crusader"},
{"Half-Track","halftrack","candc_gunrunning","halftrack"},
{"Khanjali","khanjali","candc_xmas2017","khanjali_b"},
{"Rhino Tank","Rhino","candc_default","rhino"},
{"Scarab 2","SCARAB2","mba_vehicles","scarab2"},
{"Scarab 3","SCARAB3","mba_vehicles","scarab3"},
{"Scarab","SCARAB","mba_vehicles","scarab1"},
{"Thruster","thruster","candc_xmas2017","thruster_b"},
{"Truck Cab","Barracks2","",""}
};
static std::vector<VehiclePreview> Emergency{
{"Ambulance","Ambulance","",""},
{"Buffalo (FIB)","Fbi","",""},
{"Firetruck","Firetruk","",""},
{"Granger (FIB)","Fbi2","",""},
{"Lifeguard","Lguard","",""},
{"Park Ranger","Pranger","",""},
{"Police 3","Police3","",""},
{"Police Bike","Policeb","",""},
{"Police Buffalo","Police2","",""},
{"Police Cruiser","Police","",""},
{"Police Rancher (Snow)","Policeold1","",""},
{"Police Roadcruiser","Policeold2","",""},
{"Police Riot Van","Riot","",""},
{"Police Transporter","Policet","",""},
{"Prison Bus","Pbus","candc_default","pbus"},
{"Rcv","riot2","candc_xmas2017","riot2_b"},
{"Sheriff Cruiser","Sheriff","",""},
{"Sheriff SUV","Sheriff2","",""},
{"Unmarked Police Cruiser","Police4","",""}
};
static std::vector<VehiclePreview> Service{
{"Airport Bus","Airbus","candc_default","airbus"},
{"Brickade","Brickade","candc_executive1","brickade"},
{"City Bus","Bus","candc_default","bus"},
{"Coach","Coach","candc_default","coach"},
{"Dune","Rallytruck","sssa_dlc_stunt","rallytruck"},
{"Party Bus","Pbus2","sssa_dlc_battle","pbus2"},
{"Rental Shuttle Bus","Rentalbus","candc_default","rentbus"},
{"Stanier Taxi","Taxi","",""},
{"Tourbus","Tourbus","",""},
{"Trashmaster (Rusty)","Trash2","",""},
{"Trashmaster","Trash","",""},
{"Wastelander","Wastelander","candc_importexport","wastlndr"},
};
static std::vector<VehiclePreview> Sedans{
{"Asea (snow)","Asea2","",""},
{"Asea","Asea","sssa_dlc_business","asea"},
{"Asterope","Asterope","sssa_dlc_business","astrope"},
{"Cognoscenti 55","Cog55","lgm_dlc_apartments","cognosc"},
{"Cognoscenti 55 (Armored)","Cog552","",""},
{"Declasse Premier","Premier","sssa_dlc_business","premier"},
{"Emperor (Rusty)","Emperor2","",""},
{"Emperor (Snow)","Emperor3","",""},
{"Emperor","Emperor","",""},
{"Enus Diamond","Superd","sssa_default","superd"},
{"Fugitive","Fugitive","sssa_default","fugitive"},
{"Glendale","Glendale","sssa_dlc_hipster","glendale"},
{"Karin Intruder","Intruder","sssa_dlc_business","intruder"},
{"Limo (Armored)","Limo2","",""},
{"Limo","Stretch","sssa_default","stretch"},
{"Primo (Custom)","Primo2","",""},
{"Primo","Primo","sssa_dlc_hipster","primo"},
{"Regina","Regina","sssa_dlc_hipster","regina"},
{"Romero Hearse","Romero","sssa_dlc_battle","Romero"},
{"Schafter (Armored)","Schafter5","lgm_dlc_apartments","schafter3"},
{"Schafter (CEO)","Schafter6","lgm_dlc_apartments","schafter4"},
{"Schafter","Schafter2","sssa_dlc_heist","schafter2"},
{"Stafford","Stafford","lgm_dlc_battle","stafford"},
{"Stanier","Stanier","sssa_dlc_business","stanier"},
{"Stratum","Stratum","sssa_dlc_business","stratum"},
{"Surge","Surge","sssa_dlc_heist","surge"},
{"Tailgater","Tailgater","sssa_dlc_hipster","tailgater"},
{"Vulcan Ingot","Ingot","sssa_dlc_business","ingot"},
{"Vulcar Warrener","Warrener","sssa_dlc_hipster","warrener"},
{"Washington","Washington","sssa_dlc_business","washingt"}
};
static std::vector<VehiclePreview> Industrial{
{"Bulldozer","Bulldozer","",""},
{"Cutter","Cutter","",""},
{"Dock Handler","Handler","",""},
{"Dump","Dump","candc_default","dump"},
{"Flatbed","Flatbed","",""},
{"Guardian","Guardian","sssa_dlc_heist","guardian"},
{"Mixer (Support Wheel)","Mixer2","",""},
{"Mixer","Mixer","",""},
{"Rubble","Rubble","",""},
{"Tiptruck (empty)","Tiptruck","",""},
{"Tiptruck","Tiptruck2","",""}
};
static std::vector<VehiclePreview> Compacts{
{"Asbo","asbo","sssa_dlc_casinoheist","asbo"},
{"Blista","Blista","",""},
{"Dilettante (Patrol)","Dilettante2","",""},
{"Dilettante","Dilettante","sssa_default","dilettan"},
{"Grotti Brioso (R/A)","Brioso","sssa_dlc_stunt","brioso"},
{"Issi 3","issi3","sssa_dlc_assault","issi3"},
{"Issi 4","ISSI4","mba_vehicles","issi3_c_1"},
{"Issi 5","ISSI5","mba_vehicles","issi3_c_2"},
{"Issi 6","ISSI6","mba_vehicles","issi3_c_3"},
{"Kanjo","kanjo","sssa_dlc_casinoheist","kanjo"},
{"Panto","Panto","sssa_dlc_hipster","panto"},
{"Prairie","Prairie","sssa_dlc_battle","prairie"},
{"Rhapsody","Rhapsody","sssa_dlc_hipster","rhapsody"},
{"Weeny Issi","Issi2","sssa_default","issi2"}
};
static std::vector<VehiclePreview>  Commercial{
{"Benson","Benson","",""},
{"Cerberus 2","CERBERUS2","mba_vehicles","cerberus2"},
{"Cerberus 3","CERBERUS3","mba_vehicles","cerberus3"},
{"Cerberus","CERBERUS","mba_vehicles","cerberus1"},
{"HVY Biff","Biff","",""},
{"Hauler","Hauler","",""},
{"Hauler2","Hauler2","candc_truck","cab_1"},
{"MTL Packer","Packer","",""},
{"Mule 2","Mule2","",""},
{"Mule 3","Mule3","candc_default","mule3"},
{"Mule 4","Mule4","candc_battle","mule4"},
{"Mule","Mule","candc_default","mule"},
{"Phantom Custom","phantom3","candc_truck","cab_0"},
{"Phantom Wedge","Phantom2","candc_importexport","phantom2"},
{"Phantom","Phantom","",""},
{"Pounder 2","Pounder2","candc_battle","pounder2"},
{"Pounder","Pounder","",""},
{"Stockade (Snow)","Stockade3","",""},
{"Stockade","Stockade","",""},
{"Terbyte","Terbyte","",""}
};
static std::vector<VehiclePreview> Planes{
{"Alphaz1","alphaz1","elt_dlc_smuggler","alphaz1"},
{"Avenger","avenger","candc_chopper","banner_5"},
{"Avenger2","avenger2","candc_chopper","banner_4"},
{"Besra","Besra","elt_dlc_pilot","besra"},
{"Blimp (Xero)","Blimp2","",""},
{"Blimp (atomic)","Blimp","",""},
{"Blimp 3","blimp3","elt_dlc_battle","blimp3"},
{"Bombushka","Bombushka","candc_smuggler","bombushka"},
{"Cargoplane","Cargoplane","",""},
{"Cuban 800","Cuban800","elt_default","cuban800"},
{"Dodo","Dodo","elt_default","dodo"},
{"Duster (Rusty)","Duster","elt_default","duster"},
{"Howard","Howard","elt_dlc_smuggler","howard"},
{"Hydra","Hydra","candc_default","hydra"},
{"Jet","Jet","",""},
{"Luxor (Gold)","Luxor2","elt_dlc_executive1","luxor2"},
{"Luxor","Luxor","elt_default","luxor"},
{"Mammatus","Mammatus","elt_default","mammatus"},
{"Microlight","Microlight","elt_dlc_smuggler","microlight"},
{"Miljet","Miljet","elt_dlc_pilot","miljet"},
{"Mogul","Mogul","candc_smuggler","mogul"},
{"Molotok","Molotok","candc_smuggler","molotok_b"},
{"Nimbus","Nimbus","elt_dlc_executive1","nimbus"},
{"Nokota","Nokota","candc_smuggler","nokota"},
{"P-996 Lazer","Lazer","candc_smuggler","lazer"},
{"Pyro","Pyro","candc_smuggler","pyro"},
{"Rogue","Rogue","candc_smuggler","rogue"},
{"Seabreeze","Seabreeze","elt_dlc_smuggler","seabreeze"},
{"Shamal","Shamal","elt_default","shamal"},
{"Starling","starling","candc_smuggler","starling"},
{"Strikeforce","Strikeforce","candc_battle","strikeforce"},
{"Stunt Plane","Stunt","elt_default","stunt"},
{"Titan","Titan","elt_default","titan"},
{"Tula","tula","candc_smuggler","tula"},
{"Velum (Heist)","Velum2","elt_default","velum2"},
{"Velum","Velum","elt_default","velum"},
{"Vestra","Vestra","",""},
{"Volatol","volatol","candc_xmas2017","volatol_b"}
};
static std::vector<VehiclePreview> Utility{
{"Airport Tug","Airtug","",""},
{"Army Flatbed Trailer (Empty)","Armytrailer","",""},
{"Army Flatbed Trailer (With Drill)","Armytrailer2","",""},
{"Army Fuel Tanker","Armytanker","",""},
{"Boat Trailer (With Boat)","Tr3","",""},
{"Boat Trailer","Boattrailer","",""},
{"Caddy (Golf)","Caddy","",""},
{"Caddy 2","Caddy2","foreclosures_bunker","transportation_2"},
{"Caddy 3","Caddy3","foreclosures_bunker","transportation_1"},
{"Car Transport Trailer (Empty)","Tr2","",""},
{"Car Transport Trailer","Tr4","",""},
{"Commercial Trailers 1","Trailers2","",""},
{"Commercial Trailers 2","Trailers3","",""},
{"Commercial Trailers 3","Trailers4","",""},
{"Container Trailer","Docktrailer","",""},
{"Dock Tug","Docktug","",""},
{"Fame or Shame Trailer","Tvtrailer","",""},
{"Fieldmaster Tractor (Snow)","Tractor3","",""},
{"Fieldmaster Tractor","Tractor2","",""},
{"Flatbed Trailer 1","Freighttrailer","",""},
{"Flatbed Trailer 2","Trflat","",""},
{"Fork Lift","Forklift","",""},
{"Grain Trailer","Graintrailer","",""},
{"Hay Bale Trailer","Baletrailer","",""},
{"Logging Trailer","Trailerlogs","",""},
{"Meth Lab Trailer","Proptrailer","",""},
{"Mobile Operations Center","trailerlarge","candc_truck","banner_2"},
{"Petrol Tanker Trailer (Plain)","Tanker2","",""},
{"Petrol Tanker Trailer (RON)","Tanker","",""},
{"Pickup Utility Truck","Utillitruck3","",""},
{"Plain Trailer","Trailers","",""},
{"Plumbing Utility Truck","Utillitruck2","",""},
{"Rake Trailer","Raketrailer","",""},
{"Ripley (Airport Tug)","Ripley","",""},
{"Scrap Truck","Scrap","",""},
{"Small Trailer","Trailersmall","",""},
{"Stanley Lawn Mower","Mower","",""},
{"Telephone Utility Truck","Utillitruck","",""},
{"Tow Truck (Big)","Towtruck","",""},
{"Tow Truck","Towtruck2","",""},
{"Tractor","Tractor","",""},
{"Vapid Sadler (Snow)","Sadler2","",""},
{"Vapid Sadler","Sadler","sssa_default","sadler"},
};
static std::vector<VehiclePreview> Helicopters{
{"Akula","akula","candc_xmas2017","akula_b"},
{"Annihilator","Annihilator","elt_default","annihl"},
{"Buzzard","Buzzard","candc_default","buzzard"},
{"Buzzard(Unarmed)","Buzzard2","",""},
{"Cargobob (Closed doors)","Cargobob4","",""},
{"Cargobob (Jetsam)","Cargobob2","",""},
{"Cargobob (trevor)","Cargobob3","",""},
{"Cargobob","Cargobob","candc_default","cargobob"},
{"Frogger","Frogger","elt_default","frogger"},
{"Frogger(FIB)","Frogger2","",""},
{"Havok","havok","elt_dlc_smuggler","havok"},
{"Hunter","hunter","candc_smuggler","hunter"},
{"Maverick","Maverick","elt_default","maverick"},
{"Police Maverick","Polmav","",""},
{"Savage","Savage","candc_default","savage"},
{"Sea Sparrow","SEASPARROW","elt_dlc_assault","sparrow"},
{"Skylift","Skylift","",""},
{"Supervolito (CEO)","Supervolito2","",""},
{"Supervolito","Supervolito","",""},
{"Swift (Gold)","Swift2","elt_dlc_executive1","swift2"},
{"Swift","Swift","elt_dlc_pilot","swift"},
{"Valkyrie (Unarmed)","Valkyrie2","",""},
{"Valkyrie","Valkyrie","candc_default","valkyrie"},
{"Volatus","Volatus","elt_dlc_executive1","volatus"},
};
static std::vector<VehiclePreview> Vans{
{"BF Surfer (Rusty)","Surfer2","",""},
{"BF Surfer","Surfer","sssa_dlc_hipster","surfer"},
{"Bison (Backrack)","Bison2","",""},
{"Bison (Construction)","Bison3","",""},
{"Bison","Bison","sssa_default","bison"},
{"Bobcat XL","Bobcatxl","sssa_dlc_business","bobcatxl"},
{"Boxville (Armed)","Boxville5","candc_importexport","boxville5"},
{"Boxville (Go Postal)","Boxville2","",""},
{"Boxville (Humane)","Boxville3","",""},
{"Boxville (Post OP)","Boxville4","candc_default","boxville4"},
{"Boxville","Boxville","",""},
{"Brute Pony (Business)","Pony","",""},
{"Brute Pony (Cannibus Shop)","Pony2","",""},
{"Burrito (Bug Stars)","Burrito2","",""},
{"Burrito (Construction)","Burrito4","",""},
{"Burrito (Gang 2)","Gburrito2","sssa_dlc_heist","gburrito2"},
{"Burrito (Gang)","Gburrito","",""},
{"Burrito (Snow)","Burrito5","",""},
{"Burrito (clear)","Burrito3","",""},
{"Burrito","Burrito","",""},
{"Camper","Camper","",""},
{"Journey","Journey","candc_default","journey"},
{"Minivan (Custom)","Minivan2","lsc_lowrider2","minivan2_b"},
{"Minivan","Minivan","sssa_dlc_business","minivan"},
{"Paradise","Paradise","sssa_default","paradise"},
{"Rumpo (Armored)","Rumpo3","sssa_dlc_executive_1","rumpo3_b"},
{"Rumpo (Deludamol)","Rumpo2","",""},
{"Rumpo","Rumpo","sssa_dlc_heist","rumpo"},
{"Speedo 4","Speedo4","",""},
{"Speedo 2 (Clown)","Speedo2","",""},
{"Speedo","Speedo","",""},
{"Taco Van","Taco","",""},
{"Youga (classic)","Youga2","sssa_dlc_biker","youga2"},
{"Youga","Youga","sssa_dlc_hipster","youga"}
};
static std::vector<VehiclePreview> Boats{
{"Dinghy","Dinghy","",""},
{"Dinghy (Additional light)","Dinghy2","",""},
{"Dinghy (Heist)","Dinghy3","dock_default","dinghy3"},
{"Dinghy","Dinghy4","",""},
{"Jetmax","Jetmax","dock_default","jetmax"},
{"Marquis","Marquis","dock_default","marquis"},
{"Predator (Police)","Predator","",""},
{"Seashark","Seashark","dock_default","seashark"},
{"Seashark (Lifeguard)","Seashark2","",""},
{"Seashark (Charged)","Seashark3","",""},
{"Speeder","Speeder","dock_default","speeder"},
{"Speeder (Colored)","Speeder2","",""},
{"Squalo","Squalo","dock_default","squalo"},
{"Submarine","Submersible","",""},
{"Submarine (Kraken)","Submersible2","dock_default","sub2"},
{"Suntrap","Suntrap","dock_default","suntrap"},
{"Toro","Toro","dock_default","toro"},
{"Toro (Colored)","Toro2","",""},
{"Tropic","Tropic","dock_default","tropic"},
{"Tropic (handrail)","Tropic2","",""},
{"Tug","Tug","",""}
};
static std::vector<VehiclePreview> Cycles{
{"Bmx","Bmx","pandm_default","bmx"},
{"Cruiser","Cruiser","pandm_default","cruiser"},
{"Endurex","Tribike2","pandm_default","tribike2"},
{"Fixter","Fixter","",""},
{"Scorcher","Scorcher","pandm_default","scorcher"},
{"Tri-Cycle","Tribike3","pandm_default","tribike3"},
{"Whippet","Tribike","pandm_default","tribike"}
};
static std::vector<VehiclePreview> Trains{
{"Cable Car (Mt. Chilliad)","Cablecar","",""},
{"Container Cars 2","Freightcont1","",""},
{"Container Cars 2","Freightcont2","",""},
{"Flatbed Car","Freightcar","",""},
{"Freight Train Cab","Freight","",""},
{"Grain Car","Freightgrain","",""},
{"Metro Train (Half)","Metrotrain","",""},
{"Oil Tanker Car","Tankercar","",""}
};
static std::vector<VehiclePreview> Trailer{
{ "Army Fuel Tanker", "Armytanker", "", "" },
{ "Army Flatbed Trailer (Empty)", "Armytrailer", "", "" },
{ "Army Flatbed Trailer (With Drill)", "Armytrailer2", "", "" },
{ "Hay Bale Trailer", "Baletrailer", "", "" },
{ "Boat Trailer", "Boattrailer", "", "" },
{ "Container Trailer", "Docktrailer", "", "" },
{ "Flatbed Trailer 1", "Freighttrailer", "", "" },
{ "Grain Trailer", "Graintrailer", "", "" },
{ "Meth Lab Trailer", "Proptrailer", "", "" },
{ "Rake Trailer", "Raketrailer", "", "" },
{ "Petrol Tanker Trailer (RON)", "Tanker", "", "" },
{ "Petrol Tanker Trailer (Plain)", "Tanker2", "", "" },
{ "Car Transport Trailer (Empty)", "Tr2", "", "" },
{ "Boat Trailer (With Boat)", "Tr3", "", "" },
{ "Car Transport Trailer", "Tr4", "", "" },
{ "Logging Trailer", "Trailerlogs", "", "" },
{ "Plain Trailer", "Trailers", "", "" },
{ "Commercial Trailers 1", "Trailers2", "", "" },
{ "Commercial Trailers 2", "Trailers3", "", "" },
{ "Commercial Trailers 3", "Trailers4", "", "" },
{ "Small Trailer", "Trailersmall", "", "" },
{ "Mobile Operations Center", "trailerlarge", "", "" },
{ "Flatbed Trailer 2", "Trflat", "", "" },
{ "Fame or Shame Trailer", "Tvtrailer", "", "" }
};
static std::vector<VehiclePreview> SUV{
{"Baller (CEO)","Baller6","",""},
{"Baller 2","Baller2","sssa_default","baller2"},
{"Baller LE (Armored)","Baller5","",""},
{"Baller LE LWB","Baller4","lgm_dlc_apartments","baller4"},
{"Baller LE","Baller3","lgm_dlc_apartments","baller3"},
{"Baller","Baller","",""},
{"BeeJay XL","Bjxl","sssa_dlc_battle","bjxl"},
{"Canis Seminole","Seminole","sssa_dlc_heist","seminole"},
{"Cavalcade Mk2","CAVALCADE2","sssa_dlc_business","cavcade2"},
{"Cavalcade","CAVALCADE","sssa_default","cavcade"},
{"Contender","Contender","sssa_dlc_stunt","contender"},
{"Dubsta (Flat Black)","Dubsta2","",""},
{"Dubsta","Dubsta","",""},
{"Emperor Habanero","Habanero","sssa_dlc_battle","habanero"},
{"Enus Huntley S","Huntley","lgm_dlc_business2","huntley"},
{"Fathom FQ 2","fq2","sssa_dlc_battle","fq2"},
{"Granger","Granger","sssa_dlc_business","granger"},
{"Gresley","Gresley","sssa_dlc_heist","gresley"},
{"Landstalker","Landstalker","sssa_dlc_heist","landstalker"},
{"Mammoth Patriot","Patriot","sssa_dlc_battle","patriot"},
{"Mesa (Snow)","Mesa2","",""},
{"Mesa","Mesa","candc_default","mesa"},
{"Novak","novak","lgm_dlc_vinewood","novak"},
{"Patriot 2","Patriot2","sssa_dlc_battle","patriot2"},
{"Radius","Radi","sssa_dlc_business","radi"},
{"Rebla","rebla","lgm_dlc_casinoheist","rebla"},
{"Rocoto","Rocoto","sssa_default","rocoto"},
{"Serrano","Serrano","sssa_dlc_battle","serrano"},
{"Toros","TOROS","lgm_dlc_arena","toros"},
{"Xls (Armored)","Xls2","",""},
{"Xls","Xls","lgm_dlc_executive1","xls"}
};
static std::vector<std::pair<std::string, std::vector<VehiclePreview>>> vehiclePreview{
	{"超跑 >>",Super},
	{"跑车 >>",Sports},
	{"经典跑车 >>",SportsClassics},
	{"轿跑 >>",Coupes},
	{"肌肉车 >>",Muscle},
	{"越野车 >>",Offroad},
	{"摩托车 >>",Motorcycles},
	{"军用车辆 >>",Military},
	{"应急车辆 >>",Emergency},
	{"服务车辆 >>",Service},
	{"轿车 >>",Sedans},
	{"工业车辆 >>",Industrial},
	{"小型车 >>",Compacts},
	{"商用车 >>",Commercial},
	{"飞机 >>",Planes},
	{"多用途车 >>",Utility},
	{"直升飞机 >>",Helicopters},
	{"厢式货车 >>",Vans},
	{"船 >>",Boats},
	{"自行车 >>",Cycles},
	{"火车 >>",Trains},
	{"拖车 >>",Trailer},
	{"SUV >>",SUV},
};


static unsigned int joaat(std::string input)
{
	unsigned int num1 = 0U;
	for (char c : input)
	{
		unsigned int num2 = num1 + (unsigned int)tolower(c);
		unsigned int num3 = num2 + (num2 << 10);
		num1 = num3 ^ num3 >> 6;
	}
	unsigned int num4 = num1 + (num1 << 3);
	unsigned int num5 = num4 ^ num4 >> 11;
	return num5 + (num5 << 15);
}