#pragma once
#include<vector>

struct VehiclePreview {
	std::wstring VName;
	char* VCode;
	char* TexDict;
	char* TexName;
};


static std::vector<VehiclePreview> Super{
{L"菲斯特 811","Pfister811","lgm_dlc_executive1","pfister811"},
{L"特卢菲 灵蛇","Adder","lgm_default","adder"},
{L"傲弗拉 独裁者","autarch","lgm_dlc_xmas2017","autarch_b"},
{L"冒险家 女妖 900R","Banshee2","lsc_jan2016","banshee2"},
{L"威皮 子弹","Bullet","lgm_default","bullet"},
{L"古罗帝 猎豹","Cheetah","lgm_default","cheetah"},
{L"旋风 飓风","cyclone","lgm_dlc_smuggler","cyclone"},
{L"旋风 飓风","cyclone","lgm_dlc_smuggler","cyclone"},
{L"普林西比 蹂躏者8","DEVESTE","lgm_dlc_arena","deveste"},
{L"皇霸天 ETR1","Sheava","lgm_dlc_stunt","sheava"},
{L"培罗 艾默瑞思","emerus","lgm_dlc_vinewood","emerus"},
{L"傲弗拉 本质 XXR","entity2","lgm_dlc_assault","entity2"},
{L"傲弗拉 本质 XF","Entityxf","lgm_default","entityxf"},
{L"威皮 FMJ","Fmj","lgm_dlc_executive1","fmj"},
{L"古罗帝 狂怒者","furia","lgm_dlc_casinoheist","furia"},
{L"培罗 GP1","gp1","lgm_dlc_specialraces","gp1"},
{L"佩嘉西 炼狱魔","Infernus","sssa_default","infernus"},
{L"培罗 义塔力 GTB 改装版","italigtb2","lsc_dlc_import_export","italigtb2"},
{L"培罗 义塔力 GTB","Italigtb","lsc_dlc_import_export","italigtb"},
{L"贝飞特 战兵","krieger","lgm_dlc_vinewood","krieger"},
{L"特卢飞 尼罗 改装版 Custom","Nero2","lsc_dlc_import_export","nero2_b"},
{L"特卢飞 尼罗","Nero","lsc_dlc_import_export","nero2_a"},
{L"佩嘉西 奥西里斯","Osiris","lgm_dlc_luxe","Osiris"},
{L"欧斯洛 穿刺者","Penetrator","lgm_dlc_importexport","penetrator"},
{L"爱尼仕 RE-7B","Le7b","lgm_dlc_stunt","le7b"},
{L"佩嘉西 死神","Reaper","lgm_dlc_executive1","reaper"},
{L"旋风 火箭狂雷","voltic2","candc_importexport","voltic2"},
{L"爱尼仕 S80RR","s80","lgm_dlc_vinewood","s80"},
{L"绝品 SC1","sc1","lgm_dlc_xmas2017","sc1_b"},
{L"绝致 超燃冲压","Scramjet","candc_battle","scramjet"},
{L"卡林 王者 RS","Sultanrs","lsc_jan2016","sultan2_a"},
{L"培罗 T20","T20","lgm_dlc_luxe","t20"},
{L"雪佛 泰斑","taipan","lgm_dlc_assault","taipan"},
{L"佩嘉西 风暴","Tempesta","lgm_dlc_importexport","tempesta"},
{L"佩嘉西 泰泽拉克","tezeract","lgm_dlc_assault","tezeract"},
{L"特卢菲 瑟雷斯","thrax","lgm_dlc_vinewood","thrax"},
{L"古罗帝 披治 R","turismor","lgm_dlc_business","turismor"},
{L"傲弗拉 统治者","TYRANT","lgm_dlc_assault","tyrant"},
{L"培罗 泰勒斯","Tyrus","lgm_dlc_stunt","tyrus"},
{L"佩嘉西 狂牛","Vacca","lgm_default","vacca"},
{L"浪子 瓦格纳","Vagner","lgm_dlc_gunrunning","vagner"},
{L"义警","Vigilante","candc_smuggler","vigilante"},
{L"古罗帝 幻象","visione","lgm_dlc_smuggler","visione"},
{L"旋风 狂雷","Voltic","lgm_default","voltic_tless"},
{L"古罗帝 X80 原型","Prototipo","lgm_dlc_executive1","prototipo"},
{L"欧斯洛 XA-21","xa21","lgm_dlc_gunrunning","xa21"},
{L"佩嘉西 桑托劳","Zentorno","lgm_dlc_business2","zentorno"},
{L"佩嘉西 佐卢索","zorrusso","lgm_dlc_vinewood","zorrusso"}
};
static std::vector<VehiclePreview> Sports{
{L"亚班尼 爱快","Alpha","lgm_dlc_business","alpha"},
{L"冒险家 女妖","Banshee","lgm_dlc_business2","banshee_tless"},
{L"丁卡 小型旅行家","Blista2","sssa_dlc_mp_to_sp","blista2"},
{L"古罗帝 野兽 GTS","Bestiagts","lgm_dlc_executive1","bestiagts"},
{L"丁卡 旅行家(赛车版)","blista3","",""},
{L"冒险家 探险猛牛 S","Buffalo2","sssa_dlc_hipster","buffalo"},
{L"冒险家 霜碧猛牛 S 赛车","Buffalo3","sssa_dlc_mp_to_sp","buffalo3"},
{L"冒险家 猛牛","Buffalo","sssa_dlc_hipster","buffalo"},
{L"古罗帝 汗血宝马","Carbonizzare","lgm_default","carboniz"},
{L"菲斯特 陆上彗星怀旧改装版","Comet3","lsc_dlc_import_export","comet3"},
{L"菲斯特 陆上彗星","Comet2","sssa_default","comet2"},
{L"菲斯特 彗星狩猎者","comet4","lgm_dlc_xmas2017","comet4_b"},
{L"菲斯特 陆上彗星 SR","comet5","lgm_dlc_xmas2017","comet5_b"},
{L"非凡 风情","Coquette","lgm_default","coquette"},
{L"奥北 F8 尾流王者","drafter","lgm_dlc_vinewood","drafter"},
{L"绝致 漂移坦帕","tampa2","sssa_dlc_stunt","tampa2"},
{L"爱尼仕 輓歌 RH8","Elegy2","lgm_default","elegy2"},
{L"爱尼仕 挽歌怀旧改装版","Elegy","lsc_dlc_import_export","elegy"},
{L"贝飞特 飞特者","Feltzer2","",""},
{L"培罗 PR4", "formula", "lgm_dlc_casinoheist", "formula"},
{L"欧斯洛 R88", "formula2", "lgm_dlc_casinoheist", "formula2"},
{L"威皮 闪电 GT","flashgt","lgm_dlc_assault","flashgt"},
{L"兰帕达提 复仇女神 GT","Furoregt","lgm_dlc_lts_creator","furore"},
{L"赛乐斯特 眩光","Fusilade","sssa_dlc_business2","fusilade"},
{L"卡林 福多","futo","sssa_dlc_battle","futo"},
{L"威皮 GB200","gb200","lgm_dlc_assault","gb200"},
{L"绝致 燃轨军刀","hotring","sssa_dlc_assault","hotring"},
{L"傲弗拉 焰魔狼","imorgon","lgm_dlc_casinoheist","imorgon"},
{L"威尼 天威跑车","issi7","sssa_dlc_vinewood","issi7"},
{L"古罗帝 义塔力","ITALIGTO","lgm_dlc_arena","italigto"},
{L"丁卡 小丑 赛车","jester2","sssa_dlc_christmas_2","jester2"},
{L"丁卡 弄臣经典版","jester3","lgm_dlc_assault","jester3"},
{L"丁卡 小丑","Jester","lgm_dlc_business","jester"},
{L"欧斯洛 咽喉","jugular","lgm_dlc_vinewood","jugular"},
{L"海角 变色龙","Khamelion","",""},
{L"兰帕达提 古茂田","komoda","lgm_dlc_casinoheist","komoda"},
{L"卡林骷髅马(附装甲)","kuruma2","sssa_dlc_heist","kuruma2"},
{L"卡林骷髅马","kuruma","sssa_dlc_heist","kuruma"},
{L"欧斯洛 蝗虫","locust","lgm_dlc_vinewood","locust"},
{L"欧斯洛 山猫","lynx","lgm_dlc_stunt","lynx"},
{L"浪子 马沙高 赛车","Massacro2","sssa_dlc_christmas_2","massacro2"},
{L"浪子 马沙高","Massacro","lgm_dlc_business2","massacro"},
{L"飞莎 尼欧","neo","lgm_dlc_vinewood","neo"},
{L"菲斯特  霓虹","neon","lgm_dlc_xmas2017","neon_b"},
{L"奥北 9F 敞篷版","Ninef2","lgm_default","ninef2"},
{L"奥北 9F","Ninef","sssa_default","ninef"},
{L"奥北 奥姆尼斯","Omnis","sssa_dlc_stunt","omnis"},
{L"埃努斯 帕拉刚 R","paragon","lgm_dlc_vinewood","paragon"},
{L"埃努斯 帕拉刚 R (附装甲)","paragon2","lgm_dlc_vinewood","paragon"},
{L"欧斯洛 放逐者","pariah","lgm_dlc_xmas2017","pariah_b"},
{L"麦霸子 半影使者","Penumbra","sssa_dlc_business2","penumbra"},
{L"旋风 雷电","raiden","lgm_dlc_xmas2017","raiden_b"},
{L"浪子 疾速 GT 敞篷","rapidgt2","lgm_default","rapidgt2"},
{L"浪子 疾速 GT","Rapidgt","lgm_default","rapidgt"},
{L"必福 迅猛龙","raptor","lgm_dlc_biker","raptor"},
{L"绝品 反叛者","revolter","lgm_dlc_xmas2017","revolter_b"},
{L"海岬 拉斯顿","ruston","lgm_dlc_specialraces","ruston"},
{L"贝飞特 莎夫特 加长版","schafter4","lgm_dlc_apartments","schafter4"},
{L"贝飞特 莎夫特 V12","schafter3","lgm_dlc_apartments","schafter3"},
{L"贝飞特 撞击 GT","SCHLAGEN","lgm_dlc_arena","schlagen"},
{L"贝飞特 史瓦泽","schwarzer","sssa_default","schwarze"},
{L"绝品 卫士经典版","sentinel3","sssa_dlc_xmas2017","sentinel3_b"},
{L"浪子 柒-70","Seven70","lgm_dlc_executive1","seven70"},
{L"浪子 幽鬼","specter","lsc_dlc_import_export","specter2_a"},
{L"浪子 幽鬼改装版","specter2","lsc_dlc_import_export","specter2_b"},
{L"贝飞特 斯垂特","streiter","lgm_dlc_xmas2017","streiter_b"},
{L"丁卡 斯国一","sugoi","sssa_dlc_casinoheist","sugoi"},
{L"卡林 王者","Sultan","lsc_jan2016","sultan2_a"},
{L"卡林 经典王者","sultan2","sssa_dlc_casinoheist","sultan2"},
{L"贝飞特 速雷","surano","lgm_default","surano_convertable"},
{L"兰帕达缇 逐波雷厉","tropos","sssa_dlc_stunt","tropos"},
{L"亚班尼 V-STR","vstr","lgm_dlc_casinoheist","vstr"},
{L"冒险家 迷失者","Verlierer2","lgm_dlc_apartments","verlier"},
{L"爱尼仕 科幻","ZR3802","mba_vehicles","zr3802"},
{L"爱尼仕 梦魇","ZR3803","mba_vehicles","zr3803"},
{L"爱尼仕 末日","ZR380","mba_vehicles","zr3801"}
};
static std::vector<VehiclePreview> SportsClassics{
{L"欧斯洛 炽焰","Ardent","candc_gunrunning","ardent"},
{L"兰帕达提 佳士可","casco","lgm_dlc_heist","casco"},
{L"卢恩 切布列克","cheburek","sssa_dlc_assault","cheburek"},
{L"古罗帝 猎豹经典版","Cheetah2","lgm_dlc_gunrunning","cheetah2"},
{L"非凡 风情经典","coquette2","lgm_dlc_pilot","coquette2"},
{L"英庞提 德罗索","deluxo","candc_xmas2017","deluxo_b"},
{L"威尼 王朝","dynasty","sssa_dlc_vinewood","dynasty"},
{L"福师 法加洛亚","fagaloa","sssa_dlc_assault","fagaloa"},
{L"古罗帝 GT500","gt500","lgm_dlc_xmas2017","gt500_b"},
{L"佩嘉西 炼狱魔经典版","Infernus2","lgm_dlc_specialraces","infernus2"},
{L"浪子 JB 700","jb700","lgm_default","jb700"},
{L"浪子 JB 700W","jb7002","lgm_default","jb700"},
{L"绝致 曼巴","mamba","lgm_dlc_apartments","mamba"},
{L"亚班尼 明日之星","manana","",""},
{L"兰帕达缇","michelli","sssa_dlc_assault","michelli"},
{L"佩嘉西 门罗","monroe","lgm_default","monroe"},
{L"福狮 星云涡轮","nebula","sssa_dlc_vinewood","nebula"},
{L"威皮 佩优特","Peyote","",""},
{L"兰帕达提 皮卡乐","pigalle","sssa_dlc_hipster","pigalle"},
{L"浪子 疾速 GT 经典版","rapidgt3","lgm_dlc_smuggler","rapidgt3"},
{L"威皮 随行者 Mk II","retinue2","sssa_dlc_casinoheist","retinue2"},
{L"威皮 随行者","Retinue","",""},
{L"威皮 随行者","Retinue","sssa_dlc_smuggler","retinue_b"},
{L"亚班尼 科学怪人","btype2","sssa_dlc_halloween","btype2"},
{L"亚班尼 罗斯福勇气","btype3","lgm_dlc_valentines2","roosevelt2"},
{L"亚班尼 罗斯福","btype","lgm_dlc_valentines","roosevelt"},
{L"爱尼仕 萨维特斯拉","savestra","lgm_dlc_xmas2017","savestra_b"},
{L"古罗帝 史汀格 GT","stingergt","lgm_default","stingerg"},
{L"古罗帝 史汀格","stinger","lgm_default","stinger"},
{L"贝飞特 斯特林 GT","Feltzer3","lgm_dlc_luxe","feltzer3"},
{L"欧斯洛 斯特龙伯格","stromberg","candc_xmas2017","stromberg_b"},
{L"欧斯洛 潮威","Swinger","lgm_dlc_battle","swinger"},
{L"佩嘉西 斗牛","torero","lgm_dlc_gunrunning","torero"},
{L"绝致 龙卷风","Tornado","",""},
{L"绝致 龙卷风 敞篷","Tornado2","",""},
{L"绝致 龙卷风 破旧版","Tornado3","",""},
{L"绝致 龙卷风 敞篷 破旧版","Tornado4","",""},
{L"绝致 龙卷风改装版","Tornado5","lsc_lowrider2","tornado5_a"},
{L"绝致 龙卷风破烂老爷车","tornado6","sssa_dlc_biker","tornado6"},
{L"古罗帝 远途经典版","turismo2","lgm_dlc_specialraces","turismo2"},
{L"兰帕达缇 维瑟瑞斯","viseris","lgm_dlc_xmas2017","viseris_b"},
{L"特卢菲 Z-Type","ztype","lgm_default","ztype"},
{L"卡林 190z","z190","lgm_dlc_xmas2017","z190_b"},
{L"绝品 经典锡安","zion3","sssa_dlc_vinewood","zion3"}
};
static std::vector<VehiclePreview> Coupes{
{L"埃努斯 至尊慧眼","cogcabrio","lgm_default","cogcabri"},
{L"浪子 典范","Exemplar","sssa_default","exemplar"},
{L"欧斯洛 F620","F620","sssa_dlc_business2","f620"},
{L"兰帕达提 恶龙","Felon","sssa_default","felon"},
{L"兰帕达提 恶龙 GT","Felon2","sssa_default","felon2"},
{L"欧斯洛 豺狼","Jackal","sssa_dlc_heist","jackal"},
{L"绝品 先知","Oracle","sssa_default","oracle"},
{L"绝品 先知 Mk2","oracle2","sssa_dlc_heist","oracle1"},
{L"绝品 卫士 XS","Sentinel","sssa_dlc_business2","sentinel"},
{L"绝品 卫士","Sentinel2","sssa_dlc_business2","sentinel"},
{L"埃努斯 温莎","Windsor","lgm_dlc_luxe","windsor"},
{L"埃努斯 温莎敞篷版","Windsor2","",""},
{L"绝品 锡安","Zion","sssa_default","zion"},
{L"绝品 锡安 敞篷版","Zion2","sssa_default","zion2"}
};
static std::vector<VehiclePreview> Muscle{
{L"威皮 刀片","Blade","sssa_dlc_hipster","blade"},
{L"英庞提 灭世暴徒 损坏穿模版","ruiner3","",""},
{L"亚班尼 风流海盗 定制版","Buccaneer2","lsc_default","buccaneer2_b"},
{L"亚班尼 风流海盗","Buccaneer","lsc_default","buccaneer2_a"},
{L"威皮 奇诺2","Chino2","lsc_default","chino2_a"},
{L"威皮 奇诺","Chino","lgm_dlc_luxe","chino"},
{L"威皮 克里克","CLIQUE","lgm_dlc_arena","clique"},
{L"非凡 风情黑鳍","coquette3","lgm_dlc_luxe","coquette3"},
{L"赛乐斯特 异类 ","DEVIANT","lgm_dlc_arena","deviant"},
{L"威皮 统治者 3","dominator3","sssa_dlc_assault","dominator3"},
{L"威皮 末日公路霸者","DOMINATOR4","mba_vehicles","dominato_c_1"},
{L"威皮 科幻公路霸者","DOMINATOR5","mba_vehicles","dominato_c_2"},
{L"威皮 梦魇公路霸者","DOMINATOR6","mba_vehicles","dominato_c_3"},
{L"威皮 统治者","Dominator","sssa_dlc_business2","dominato"},
{L"英奔堤 死亡公爵","Dukes2","candc_default","dukes"},
{L"英奔堤 公爵","Dukes","sssa_dlc_mp_to_sp","dukes"},
{L"威皮 爱利","ellie","sssa_dlc_assault","ellie"},
{L"威拉德 宗教改装巨轮版","Faction3","lsc_lowrider2","faction3_b"},
{L"威拉德 宗教改装版","Faction2","lsc_lowrider2","faction3_a"},
{L"威拉德 宗派","Faction","lsc_default","faction2_a"},
{L"冒险家 红木牌铁腕 赛车","Gauntlet2","sssa_dlc_mp_to_sp","gauntlet2"},
{L"冒险家 经典铁腕","gauntlet3","sssa_dlc_vinewood","gauntlet3"},
{L"冒险家 铁腕地狱之火","gauntlet4","sssa_dlc_vinewood","gauntlet4"},
{L"冒险家 铁腕","Gauntlet","sssa_default","gauntlet"},
{L"亚班尼 赫尔墨斯","hermes","sssa_dlc_xmas2017","hermes_b"},
{L"威皮 热情使徒","Hotknife","lgm_default","hotknife"},
{L"威皮 赫斯勒","hustler","lgm_dlc_xmas2017","hustler_b"},
{L"绝致 刺刑官","IMPALER","mba_vehicles","impaler"},
{L"绝致 刺刑官","impaler","sssa_dlc_vinewood","impaler"},
{L"绝致 末日刺刑官","IMPALER2","mba_vehicles","impaler_c_1"},
{L"绝致 科幻刺刑官","IMPALER3","mba_vehicles","impaler_c_2"},
{L"绝致 梦魇刺刑官","IMPALER4","mba_vehicles","impaler_c_3"},
{L"威皮 科幻凯撒大帝","IMPERATOR2","mba_vehicles","imperator2"},
{L"威皮 梦魇凯撒大帝","IMPERATOR3","mba_vehicles","imperator3"},
{L"威皮 末日凯撒大帝","IMPERATOR","mba_vehicles","imperator1"},
{L"亚班尼 闹鬼灵车","lurcher","sssa_dlc_halloween","lurcher"},
{L"绝致 月光改装版","Moonbeam2","lsc_default","moonbeam2"},
{L"绝致 月光","Moonbeam","",""},
{L"英庞提 暗夜魅影","nightshade","lgm_dlc_apartments","niteshad"},
{L"威皮 佩优特风火轮","peyote2","sssa_dlc_vinewood","peyote2"},
{L"英奔堤 不死鸟","phoenix","",""},
{L"雪佛 斗牛士","picador","sssa_dlc_hipster","picador"},
{L"威皮 统治者 赛车","Dominator2","sssa_dlc_mp_to_sp","dominator2"},
{L"冒险家 老爷货车 (破旧版)","ratloader","sssa_dlc_valentines","rloader"},
{L"冒险家 老爷货车","ratloader2","sssa_dlc_christmas_2","rloader2"},
{L"英奔堤 灭世暴徒 2000","ruiner2","candc_importexport","ruiner2"},
{L"英奔堤 灭世暴徒","ruiner","sssa_dlc_battle","ruiner"},
{L"绝致 涡轮剑齿虎","Sabregt","",""},
{L"绝致 军刀涡轮改装版","Sabregt2","lsc_lowrider2","sabregt2_a"},
{L"威皮 斯拉姆万 LostMC","Slamvan2","",""},
{L"威皮 斯拉姆万 3","Slamvan3","lsc_lowrider2","slamvan3_b"},
{L"威皮 末日大满贯皮卡","SLAMVAN4","mba_vehicles","slamvan_c_1"},
{L"威皮 科幻大满贯皮卡","SLAMVAN5","mba_vehicles","slamvan_c_2"},
{L"威皮 梦魇大满贯皮卡","SLAMVAN6","mba_vehicles","slamvan_c_3"},
{L"威皮 斯拉姆万","Slamvan","sssa_dlc_christmas_2","slamvan"},
{L"绝致 吃得饱汉堡种马 赛车","stalion2","sssa_dlc_mp_to_sp","stalion2"},
{L"绝致 吃得饱汉堡种马","Stalion","sssa_dlc_mp_to_sp","stallion"},
{L"绝致 武装坦帕","tampa3","candc_gunrunning","tampa3"},
{L"绝致 坦帕","Tampa","sssa_dlc_christmas_3","tampa"},
{L"绝致 郁金","TULIP","sssa_dlc_arena","tulip"},
{L"绝致 瓦魔狮","VAMOS","sssa_dlc_arena","vamos"},
{L"绝致 活力够","Vigero","sssa_default","vigero"},
{L"郭追里 经典室女座改装版","Virgo2","lsc_lowrider2","virgo2_a"},
{L"郭追里 经典室女座","Virgo3","lsc_lowrider2","virgo2_b"},
{L"亚班尼 室女座","Virgo","lgm_dlc_luxe","virgo"},
{L"绝致 巫毒","Voodoo2","lsc_default","voodoo_b"},
{L"绝致 巫毒改装版","Voodoo","lsc_default","voodoo_a"},
{L"绝致 优胜美地","yosemite","sssa_dlc_xmas2017","yosemite_b"},
{L"绝致 甩尾优胜美地","yosemite2","sssa_dlc_casinoheist","yosemite2"}
};
static std::vector<VehiclePreview> Offroad{
{L"毕福 沙丘征服者","bfinjection","sssa_default","bfinject"},
{L"毕福 必浮塔","Bifta","sssa_default","bifta"},
{L"长崎 (崔佛所有)","Blazer3","sssa_dlc_hipster","blazer3"},
{L"长崎 水陆烈焰","Blazer5","candc_importexport","blazer5"},
{L"长崎 烈焰救生型","Blazer2","",""},
{L"长崎 烈焰","Blazer","sssa_default","blazer"},
{L"长崎 街头烈焰","Blazer4","sssa_dlc_biker","blazer4"},
{L"卡尼斯 万用行者","Bodhi2","sssa_default","bodhi2"},
{L"旋风 斗殴者","Brawler","lgm_dlc_luxe","brawler"},
{L"贝飞特 科幻捍士","BRUISER2","mba_vehicles","bruiser_c_2"},
{L"贝飞特 梦魇捍士","BRUISER3","mba_vehicles","bruiser_c_3"},
{L"贝飞特 末日捍士","BRUISER","mba_vehicles","bruiser_c_1"},
{L"绝致 科幻布鲁图斯","BRUTUS2","mba_vehicles","brutus2"},
{L"绝致 梦魇布鲁图斯","BRUTUS3","mba_vehicles","brutus3"},
{L"绝致 末日布鲁图斯","BRUTUS","mba_vehicles","brutus1"},
{L"威皮 拉卡拉卡四驱车","caracara2","sssa_dlc_vinewood","caracara2"},
{L"威皮 卡拉卡拉","caracara","candc_assault","caracara"},
{L"贝飞特 迪布达 6x6","Dubsta3","candc_default","dubsta3"},
{L"必福 沙丘 FAV","Dune3","candc_gunrunning","dune3"},
{L"毕福 沙丘魔宝","Dune","sssa_default","dune"},
{L"冒险家 越野游侠","Dloader","",""},
{L"卡林 艾维尔隆","everon","sssa_dlc_casinoheist","everon"},
{L"卡尼斯 自由行者","Freecrawler","lgm_dlc_battle","freecrawler"},
{L"爱尼仕 恶人","hellion","sssa_dlc_vinewood","hellion"},
{L"HVY 叛乱分子皮卡改装版","Insurgent3","",""},
{L"HVY 叛乱分子皮卡改装版","Insurgent3","ua_generic","ua_unlock_11"},
{L"HVY 叛乱分子","Insurgent","candc_default","insurgent"},
{L"HVY 叛乱分子 机枪版","Insurgent2","candc_default","insurgent"},
{L"卡尼斯 喀拉哈里","Kalahari","sssa_default","kalahari"},
{L"卡尼斯 卡马乔","kamacho","sssa_dlc_xmas2017","kamacho_b"},
{L"雪佛 马绍尔","marshall","candc_default","marshall"},
{L"HVY 威吓者","Menacer","candc_battle","menacer"},
{L"卡尼斯 岩魔","Mesa3","candc_default","mesa3"},
{L"冒险家 末日大脚怪","MONSTER3","mba_vehicles","monster_c_1"},
{L"冒险家 科幻大脚怪","MONSTER4","mba_vehicles","monster_c_2"},
{L"冒险家 梦魇大脚怪","MONSTER5","mba_vehicles","monster_c_3"},
{L"HVY 夜鲨","nightshark","candc_gunrunning","nightshark"},
{L"长崎 亡命之徒","outlaw","sssa_dlc_casinoheist","outlaw"},
{L"斜面魔宝(带顶棚)","Dune4","",""},
{L"斜面魔宝","Dune5","candc_importexport","dune5"},
{L"绝致 蓝彻 XL (雪地版)","Rancherxl2","",""},
{L"绝致 蓝彻 XL","Rancherxl","sssa_dlc_business","rancherx"},
{L"RC 匪徒","RCBANDITO","sssa_dlc_arena","rcbandito"},
{L"卡林 叛逆男女 破旧版","Rebel2","sssa_dlc_hipster","rebel2"},
{L"卡林 叛逆男女","Rebel","sssa_default","rebel"},
{L"威皮 利雅塔","riata","sssa_dlc_xmas2017","riata_b"},
{L"威皮 大脚霸王 XL","Sandking","sssa_default","sandking_b"},
{L"威皮 大脚霸王 SWB","Sandking2","sssa_default","sandkin_2b"},
{L"冒险家 星际码头","Dune2","",""},
{L"卡林 铁尼高改装版","Technical3","",""},
{L"卡林 水陆铁尼高","Technical2","candc_importexport","technical2"},
{L"卡林 铁尼高改装版","Technical3","ua_generic","ua_unlock_15"},
{L"卡林 铁尼高 带机枪","Technical","candc_default","technical"},
{L"威皮 解放者","monster","candc_default","monster"},
{L"威皮 沙漠突击","TrophyTruck2","sssa_dlc_stunt","trophy2"},
{L"威皮 越野卡车","TrophyTruck","sssa_dlc_stunt","trophy"},
{L"麦斯威尔 流浪者","vagrant","sssa_dlc_casinoheist","vagrant"},
{L"卢恩 萨巴","Zhaba","",""},

};
static std::vector<VehiclePreview> Motorcycles{
{L"丁卡 街头恶魔","Akuma","sssa_default","akuma"},
{L"LCC 阿瓦鲁斯","Avarus","sssa_dlc_biker","avarus"},
{L"长崎 BF400","BF400","sssa_dlc_stunt","bf400"},
{L"西部 驮兽","Bagger","sssa_dlc_biker","bagger"},
{L"佩嘉西 801RR 巴提 (赛车)","BATI2","sssa_default","bati2"},
{L"佩嘉西 801 巴提","BATI","sssa_default","bati"},
{L"长崎 碳纤维 RS 型","CARBONRS","lgm_default","carbon"},
{L"长崎 奇美拉","CHIMERA","sssa_dlc_biker","chimera"},
{L"西部 高潮","CLIFFHANGER","sssa_dlc_stunt","cliffhanger"},
{L"西部 恶魔 2","DAEMON2","sssa_dlc_biker","daemon2"},
{L"西部 恶魔","DAEMON","",""},
{L"西部 科幻丧尸","DEATHBIKE2","mba_vehicles","deathbike_c_2"},
{L"西部 梦魇丧尸","DEATHBIKE3","mba_vehicles","deathbike_c_3"},
{L"西部 末日丧尸 ","DEATHBIKE","mba_vehicles","deathbike_c_1"},
{L"诗津 亵渎者","DEFILER","sssa_dlc_biker","defiler"},
{L"普林西比 蒂雅布萝改装版","DIABLOUS2","lsc_dlc_import_export","diablous2"},
{L"普林西比 蒂雅布萝","DIABLOUS","",""},
{L"丁卡 双T","DOUBLE","sssa_default","double"},
{L"丁卡 安杜罗","ENDURO","sssa_dlc_heist","enduro"},
{L"佩嘉西 爱时吉","ESSKEY","sssa_dlc_biker","esskey"},
{L"佩嘉西 FCR 1000 改装版","FCR2","lsc_dlc_import_export","fcr2_b"},
{L"佩嘉西 FCR 1000","FCR","lsc_dlc_import_export","fcr2_a"},
{L"佩嘉西 费甲欧摩登版 Custom","FAGGIO3","sssa_dlc_biker","faggio3"},
{L"佩嘉西 费甲欧","FAGGIO","sssa_default","faggio"},
{L"佩嘉西 小绵羊","FAGGIO2","sssa_dlc_biker","faggion"},
{L"西部 石像鬼","GARGOYLE","sssa_dlc_stunt","gargoyle"},
{L"诗津 白鸟竞速版","HAKUCHOU2","lgm_dlc_biker","hakuchou2"},
{L"诗津 白鸟","HAKUCHOU","sssa_dlc_lts_creator","hakuchou"},
{L"LCC 迷魅光轮","HEXER","sssa_default","hexer"},
{L"LCC 创新","INNOVATION","sssa_dlc_lts_creator","innovation"},
{L"太平洋抢劫动力回收摩托","LECTRO","lgm_dlc_heist","lectro"},
{L"麦霸子 曼切兹","MANCHEZ","sssa_dlc_biker","manchez"},
{L"准则 复仇女神","NEMESIS","sssa_dlc_heist","nemesis"},
{L"西部 夜刃","NIGHTBLADE","sssa_dlc_biker","nightblade"},
{L"佩嘉西 暴君 Mk II","Oppressor2","candc_battle","oppressor2"},
{L"佩嘉西 暴君","Oppressor","candc_gunrunning","oppressor"},
{L"诗津 PCJ 600","PCJ","sssa_default","pcj"},
{L"西部 破烂摩托车","RATBIKE","sssa_dlc_biker","ratbike"},
{L"西部 狂暴火箭","rrocket","lgm_dlc_vinewood","rrocket"},
{L"佩嘉西 恶霸","RUFFIAN","sssa_default","ruffian"},
{L"麦霸子 桑切斯","SANCHEZ2","sssa_default","sanchez2"},
{L"麦霸子 桑切斯 (涂装)","SANCHEZ","sssa_default","sanchez"},
{L"LCC 圣驹","SANCTUS","sssa_dlc_biker","sanctus"},
{L"长崎 圣太郎","SHOTARO","lgm_dlc_biker","shotaro"},
{L"西部 君主","SOVEREIGN","",""},
{L"长崎 神行客","stryder","lgm_dlc_casinoheist","stryder"},
{L"丁卡 猛冲","THRUST","lgm_dlc_business2","thrust"},
{L"诗津 威德","VADER","sssa_default","vader"},
{L"丁卡 保卫者","VINDICATOR","lgm_dlc_luxe","vindicator"},
{L"佩嘉西 漩涡","VORTEX","sssa_dlc_biker","vortex"},
{L"西部 恶狼克星","WOLFSBANE","sssa_dlc_biker","wolfsbane"},
{L"西部 碎尸者","ZOMBIEB","sssa_dlc_biker","zombieb"},
{L"西部 鞭尸者","ZOMBIEA","sssa_dlc_biker","zombiea"}
};
static std::vector<VehiclePreview> Military{
{L"HVY APC","apc","candc_gunrunning","apc"},
{L"冯·伏厄 防空拖车","Trailersmall2","candc_gunrunning","trsmall2"},
{L"地霸王","Barracks3","",""},
{L"地霸王2","Barracks","candc_default","barracks"},
{L"巴拉杰","barrage","candc_xmas2017","barrage_b"},
{L"切尔诺伯格","chernobog","candc_xmas2017","chernobog_b"},
{L"卡尼斯 傲世铁骑","Crusader","candc_default","crusader"},
{L"冒险家 半履战车","halftrack","candc_gunrunning","halftrack"},
{L"TM-02 可汗贾利","khanjali","candc_xmas2017","khanjali_b"},
{L"犀式坦克","Rhino","candc_default","rhino"},
{L"HVY 科幻圣甲虫","SCARAB2","mba_vehicles","scarab2"},
{L"HVY 梦魇圣甲虫","SCARAB3","mba_vehicles","scarab3"},
{L"HVY 末日圣甲虫","SCARAB","mba_vehicles","scarab1"},
{L"巨象 推进者","thruster","candc_xmas2017","thruster_b"},
{L"HVY 拖车型地霸王","Barracks2","",""}
};
static std::vector<VehiclePreview> Emergency{
{L"救护车","Ambulance","",""},
{L"FIB 公务车","Fbi","",""},
{L"消防车","Firetruk","",""},
{L"FIB 公务车 SUV版","Fbi2","",""},
{L"沙滩急救车","Lguard","",""},
{L"国家公园警用车","Pranger","",""},
{L"警用巡逻车3","Police3","",""},
{L"警用机车","Policeb","",""},
{L"警用巡逻车2","Police2","",""},
{L"警用巡逻车1","Police","",""},
{L"警用吉普车 (雪地版)","Policeold1","",""},
{L"警用公路巡逻车 (雪地版)","Policeold2","",""},
{L"警用防暴车","Riot","",""},
{L"警用运输车","Policet","",""},
{L"移监巴士","Pbus","candc_default","pbus"},
{L"防爆车","riot2","candc_xmas2017","riot2_b"},
{L"威皮 警长专用车","Sheriff","",""},
{L"威皮 警用SUV","Sheriff2","",""},
{L"威皮 无标志巡逻车","Police4","",""}
};
static std::vector<VehiclePreview> Service{
{L"机场巴士","Airbus","candc_default","airbus"},
{L"MTL 布里凯德","Brickade","candc_executive1","brickade"},
{L"城市巴士","Bus","candc_default","bus"},
{L"白狗巴士","Coach","candc_default","coach"},
{L"MTL 沙丘","Rallytruck","sssa_dlc_stunt","rallytruck"},
{L"音乐节巴士","Pbus2","sssa_dlc_battle","pbus2"},
{L"租用接驳巴士","Rentalbus","candc_default","rentbus"},
{L"威皮 出租车","Taxi","",""},
{L"旅游巴士","Tourbus","",""},
{L"垃圾大王 (破旧版)","Trash2","",""},
{L"垃圾大王","Trash","",""},
{L"MTL 拓荒者","Wastelander","candc_importexport","wastlndr"},
};
static std::vector<VehiclePreview> Sedans{
{L"绝致 海致 (雪地版)","Asea2","",""},
{L"绝致 海致","Asea","sssa_dlc_business","asea"},
{L"卡林 爱硕普","Asterope","sssa_dlc_business","astrope"},
{L"埃努斯 至尊慧眼 55","Cog55","lgm_dlc_apartments","cognosc"},
{L"埃努斯 至尊慧眼 55 (装甲版)","Cog552","",""},
{L"绝致 统领","Premier","sssa_dlc_business","premier"},
{L"亚班尼 皇霸天 (破旧版)","Emperor2","",""},
{L"亚班尼 皇霸天 (雪地版)","Emperor3","",""},
{L"亚班尼 皇霸天","Emperor","",""},
{L"埃努斯 金钻耀星","Superd","sssa_default","superd"},
{L"雪佛 流星","Fugitive","sssa_default","fugitive"},
{L"贝飞特 格伦戴尔","Glendale","sssa_dlc_hipster","glendale"},
{L"卡林 入侵者","Intruder","sssa_dlc_business","intruder"},
{L"贝飞特 武装礼车","Limo2","",""},
{L"亚班尼 加长型礼车","Stretch","sssa_default","stretch"},
{L"亚班尼 初代 定制","Primo2","",""},
{L"亚班尼 初代","Primo","sssa_dlc_hipster","primo"},
{L"敦追里 女皇","Regina","sssa_dlc_hipster","regina"},
{L"烈火马 钢骨灵车","Romero","sssa_dlc_battle","Romero"},
{L"贝飞特 莎夫特 V12 装甲版","Schafter5","lgm_dlc_apartments","schafter3"},
{L"贝飞特 莎夫特 加长版 装甲版","Schafter6","lgm_dlc_apartments","schafter4"},
{L"贝飞特 莎夫特","Schafter2","sssa_dlc_heist","schafter2"},
{L"埃努斯 斯塔福德","Stafford","lgm_dlc_battle","stafford"},
{L"威皮 史塔尼亚","Stanier","sssa_dlc_business","stanier"},
{L"赛柯尼安 地层先锋","Stratum","sssa_dlc_business","stratum"},
{L"雪佛 奔腾","Surge","sssa_dlc_heist","surge"},
{L"奥北 密探","Tailgater","sssa_dlc_hipster","tailgater"},
{L"福狮 英卡特","Ingot","sssa_dlc_business","ingot"},
{L"福狮 守护星","Warrener","sssa_dlc_hipster","warrener"},
{L"亚班尼 华盛顿","Washington","sssa_dlc_business","washingt"}
};
static std::vector<VehiclePreview> Industrial{
{L"HVY 推土机","Bulldozer","",""},
{L"HVY 钻洞机","Cutter","",""},
{L"码头装卸车","Handler","",""},
{L"HVY 矿石搬运车","Dump","candc_default","dump"},
{L"MTL 平板拖车","Flatbed","",""},
{L"威皮 守护者","Guardian","sssa_dlc_heist","guardian"},
{L"HVY 混凝土搅拌车 (带滚轮)","Mixer2","",""},
{L"HVY 混凝土搅拌车","Mixer","",""},
{L"乔氏 砂通天","Rubble","",""},
{L"威霸 工地倾卸车 (单轮款)","Tiptruck","",""},
{L"威霸 工地倾卸车","Tiptruck2","",""}
};
static std::vector<VehiclePreview> Compacts{
{L"麦斯威尔 阿斯波","asbo","sssa_dlc_casinoheist","asbo"},
{L"丁卡 旅行家","Blista","",""},
{L"卡林 爱快名人油电车 (FlyUS)","Dilettante2","",""},
{L"卡林 爱快名人油电车","Dilettante","sssa_default","dilettan"},
{L"古罗帝 精力霸 R/A","Brioso","sssa_dlc_stunt","brioso"},
{L"威尼 天威经典版","issi3","sssa_dlc_assault","issi3"},
{L"威尼 末日天威","ISSI4","mba_vehicles","issi3_c_1"},
{L"威尼 科幻天威","ISSI5","mba_vehicles","issi3_c_2"},
{L"威尼 梦魇天威","ISSI6","mba_vehicles","issi3_c_3"},
{L"丁卡 旅行家环状","kanjo","sssa_dlc_casinoheist","kanjo"},
{L"贝飞特 哑剧","Panto","sssa_dlc_hipster","panto"},
{L"包洛坎 原野行者","Prairie","sssa_dlc_battle","prairie"},
{L"绝致 狂想曲","Rhapsody","sssa_dlc_hipster","rhapsody"},
{L"威尼 天威","Issi2","sssa_default","issi2"}
};
static std::vector<VehiclePreview>  Commercial{
{L"威皮 班森","Benson","",""},
{L"MTL 科幻地狱犬","CERBERUS2","mba_vehicles","cerberus2"},
{L"MTL 梦魇地狱犬","CERBERUS3","mba_vehicles","cerberus3"},
{L"MTL 末日地狱犬","CERBERUS","mba_vehicles","cerberus1"},
{L"HVY 倾卸车","Biff","",""},
{L"乔氏 搬运者","Hauler","",""},
{L"乔氏 搬运者改装版","Hauler2","candc_truck","cab_1"},
{L"MTL 车辆运送车","Packer","",""},
{L"麦霸子 猛骡(外观2)","Mule2","",""},
{L"麦霸子 猛骡 (普通)","Mule3","candc_default","mule3"},
{L"麦霸子 猛骡 改装款","Mule4","candc_battle","mule4"},
{L"麦霸子 猛骡(外观1)","Mule","candc_default","mule"},
{L"乔氏 魅影改装版","phantom3","candc_truck","cab_0"},
{L"乔氏 尖锥魅影","Phantom2","candc_importexport","phantom2"},
{L"乔氏 魅影","Phantom","",""},
{L"MTL 跑德 改装版","Pounder2","candc_battle","pounder2"},
{L"MTL 跑德","Pounder","",""},
{L"威霸 拦截者 (雪地版)","Stockade3","",""},
{L"威霸 拦截者","Stockade","",""},
{L"贝飞特 惊骇位元","Terbyte","",""}
};
static std::vector<VehiclePreview> Planes{
{L"白金汉 阿尔法-Z1","alphaz1","elt_dlc_smuggler","alphaz1"},
{L"巨象 复仇者 螺旋桨展开","avenger","candc_chopper","banner_5"},
{L"巨象 复仇者 螺旋桨收起","avenger2","candc_chopper","banner_4"},
{L"西部 雀鹰 喷射型","Besra","elt_dlc_pilot","besra"},
{L"希罗飞艇","Blimp2","",""},
{L"原子飞艇","Blimp","",""},
{L"飞艇","blimp3","elt_dlc_battle","blimp3"},
{L"RM-10 邦布什卡","Bombushka","candc_smuggler","bombushka"},
{L"客机 任务道具飞机","Cargoplane","",""},
{L"西部 古邦 800","Cuban800","elt_default","cuban800"},
{L"嘟嘟鸟水上飞机","Dodo","elt_default","dodo"},
{L"西部 洒药机","Duster","elt_default","duster"},
{L"白金汉 霍华德 NX-25","Howard","elt_dlc_smuggler","howard"},
{L"九头蛇战斗机","Hydra","candc_default","hydra"},
{L"喷射机 B747","Jet","",""},
{L"白金汉 夏马尔客机","Luxor2","elt_dlc_executive1","luxor2"},
{L"白金汉 乐梭","Luxor","elt_default","luxor"},
{L"乔氏 天行巨兽","Mammatus","elt_default","mammatus"},
{L"长崎 鸿毛","Microlight","elt_dlc_smuggler","microlight"},
{L"白金汉 军用喷射机","Miljet","elt_dlc_pilot","miljet"},
{L"巨象 莫古尔","Mogul","candc_smuggler","mogul"},
{L"V-65 莫洛托克","Molotok","candc_smuggler","molotok_b"},
{L"白金汉 灵气号","Nimbus","elt_dlc_executive1","nimbus"},
{L"P-45 诺克塔","Nokota","candc_smuggler","nokota"},
{L"乔氏 P-996 天煞 战机","Lazer","candc_smuggler","lazer"},
{L"白金汉 狂焰","Pyro","candc_smuggler","pyro"},
{L"西部 恶徒","Rogue","candc_smuggler","rogue"},
{L"西部 海风","Seabreeze","elt_dlc_smuggler","seabreeze"},
{L"白金汉 夏玛尔客机","Shamal","elt_default","shamal"},
{L"LF-22 星椋","starling","candc_smuggler","starling"},
{L"B-11 突击之力","Strikeforce","candc_battle","strikeforce"},
{L"特技飞机","Stunt","elt_default","stunt"},
{L"泰坦军用运输机","Titan","elt_default","titan"},
{L"巨象 图拉","tula","candc_smuggler","tula"},
{L"乔氏 梅杜莎 (5座)","Velum2","elt_default","velum2"},
{L"乔氏 梅杜莎 (4座)","Velum","elt_default","velum"},
{L"白金汉 威斯特拉","Vestra","",""},
{L"沃拉托 (炸弹投放)","volatol","candc_xmas2017","volatol_b"}
};
static std::vector<VehiclePreview> Utility{
{L"机场拖车","Airtug","",""},
{L"军用平板挂车 (空)","Armytrailer","",""},
{L"军用平板挂车 (附带钻头车)","Armytrailer2","",""},
{L"军用油罐挂车","Armytanker","",""},
{L"拖船半挂(带船)","Tr3","",""},
{L"拖船半挂","Boattrailer","",""},
{L"高尔夫球车","Caddy","",""},
{L"高尔夫球车 露天","Caddy2","foreclosures_bunker","transportation_2"},
{L"高尔夫球车 地堡","Caddy3","foreclosures_bunker","transportation_1"},
{L"运车挂车 (空)","Tr2","",""},
{L"运车挂车","Tr4","",""},
{L"挂车厢 (Pibwasser)","Trailers2","",""},
{L"挂车厢 (Big Good)","Trailers3","",""},
{L"挂车厢","Trailers4","",""},
{L"挂车 (无厢)","Docktrailer","",""},
{L"码头拖车","Docktug","",""},
{L"挂车厢 (Fame or Shame)","Tvtrailer","",""},
{L"史丹利 农耕机 (雪地版)","Tractor3","",""},
{L"史丹利 农耕机","Tractor2","",""},
{L"平板挂车 (长)","Freighttrailer","",""},
{L"平板挂车","Trflat","",""},
{L"HVY 推高机","Forklift","",""},
{L"粮食拖车","Graintrailer","",""},
{L"干草捆挂车","Baletrailer","",""},
{L"无厢挂车","Trailerlogs","",""},
{L"道具拖车","Proptrailer","",""},
{L"移动作战中心挂车","trailerlarge","candc_truck","banner_2"},
{L"油罐车 (无字)","Tanker2","",""},
{L"油罐车 (RON)","Tanker","",""},
{L"公共事业皮卡车","Utillitruck3","",""},
{L"平板挂车","Trailers","",""},
{L"公共事业卡车","Utillitruck2","",""},
{L"耙子车头","Raketrailer","",""},
{L"机场牵引车","Ripley","",""},
{L"废五金回收车","Scrap","",""},
{L"小型挂车","Trailersmall","",""},
{L"割草车","Mower","",""},
{L"公共事业卡车 电话抢修","Utillitruck","",""},
{L"拖吊车","Towtruck","",""},
{L"拖吊车 (破旧版)","Towtruck2","",""},
{L"牵引机 (破旧版)","Tractor","",""},
{L"威皮 沙德勒 (雪地版)","Sadler2","",""},
{L"威皮 沙德勒","Sadler","sssa_default","sadler"},
};
static std::vector<VehiclePreview> Helicopters{
{L"阿库拉","akula","candc_xmas2017","akula_b"},
{L"歼灭者直升机","Annihilator","elt_default","annihl"},
{L"长崎 兀鹰攻击直升机","Buzzard","candc_default","buzzard"},
{L"长崎 兀鹰直升机","Buzzard2","",""},
{L"运兵直升机 (关门)","Cargobob4","",""},
{L"西部 运兵直升机 喷气式","Cargobob2","",""},
{L"西部 运兵直升机 (TPE)","Cargobob3","",""},
{L"西部 运兵直升机 迷彩","Cargobob","candc_default","cargobob"},
{L"穿梭者","Frogger","elt_default","frogger"},
{L"穿梭者(FIB)","Frogger2","",""},
{L"长崎 浩劫者","havok","elt_dlc_smuggler","havok"},
{L"FH-1 猎杀者","hunter","candc_smuggler","hunter"},
{L"西部 小蛮牛","Maverick","elt_default","maverick"},
{L"西部 小蛮牛 (警用)","Polmav","",""},
{L"白金汉 武装直升机","Savage","candc_default","savage"},
{L"海雀","SEASPARROW","elt_dlc_assault","sparrow"},
{L"HVY 吊挂直升机","Skylift","",""},
{L"白金汉 超级沃力托碳纤版","Supervolito2","",""},
{L"白金汉 超级沃力托","Supervolito","",""},
{L"白金汉 斯威夫特豪华版","Swift2","elt_dlc_executive1","swift2"},
{L"白金汉 斯威夫特","Swift","elt_dlc_pilot","swift"},
{L"女武神","Valkyrie2","",""},
{L"女武神 (装甲版)","Valkyrie","candc_default","valkyrie"},
{L"白金汉 弗拉图斯","Volatus","elt_dlc_executive1","volatus"},
};
static std::vector<VehiclePreview> Vans{
{L"毕福 乘风 (破旧版)","Surfer2","",""},
{L"毕福 乘风","Surfer","sssa_dlc_hipster","surfer"},
{L"冒险家 野牛 (带后备架)","Bison2","",""},
{L"冒险家 野牛 (带顶架)","Bison3","",""},
{L"冒险家 野牛","Bison","sssa_default","bison"},
{L"威皮 熊猫 XL","Bobcatxl","sssa_dlc_business","bobcatxl"},
{L"威霸 厢村 (装甲版)","Boxville5","candc_importexport","boxville5"},
{L"威霸 厢村 (Go Postal)","Boxville2","",""},
{L"威霸 厢村 (人道实验室)","Boxville3","",""},
{L"威霸 厢村 (Post OP)","Boxville4","candc_default","boxville4"},
{L"威霸 厢村 (W & P)","Boxville","",""},
{L"威霸 小马 (商务)","Pony","",""},
{L"威霸 小马 (大麻商店)","Pony2","",""},
{L"绝致 屌客 (Bug Stars)","Burrito2","",""},
{L"绝致 屌客 (Construction)","Burrito4","",""},
{L"绝致 屌客帮派版 (Gang)","Gburrito2","sssa_dlc_heist","gburrito2"},
{L"绝致 屌客帮派版 (The Lost MC)","Gburrito","",""},
{L"绝致 屌客 (雪地版)","Burrito5","",""},
{L"绝致 屌客","Burrito3","",""},
{L"绝致 屌客 (Graphics)","Burrito","",""},
{L"威霸 露营车","Camper","",""},
{L"赛柯尼安 安旅者","Journey","candc_default","journey"},
{L"威皮 迷你厢型车(定制版)","Minivan2","lsc_lowrider2","minivan2_b"},
{L"威皮 迷你厢型车","Minivan","sssa_dlc_business","minivan"},
{L"冒险家 天堂","Paradise","sssa_default","paradise"},
{L"冒险家 澜波 (装甲版)","Rumpo3","sssa_dlc_executive_1","rumpo3_b"},
{L"冒险家 澜波 (Deludamol)","Rumpo2","",""},
{L"冒险家 澜波 (Weazel News)","Rumpo","sssa_dlc_heist","rumpo"},
{L"威皮 劲速 改装款","Speedo4","",""},
{L"威皮 劲速2","Speedo2","",""},
{L"威皮 劲速","Speedo","",""},
{L"玉米饼餐车","Taco","",""},
{L"冒险家 游侠 (经典)","Youga2","sssa_dlc_biker","youga2"},
{L"冒险家 游侠","Youga","sssa_dlc_hipster","youga"}
};
static std::vector<VehiclePreview> Boats{
{L"长崎 小艇","Dinghy","",""},
{L"长崎 小艇 (附加光源)","Dinghy2","",""},
{L"长崎 小艇 (抢劫用)","Dinghy3","dock_default","dinghy3"},
{L"长崎 小艇 (黑白配饰)","Dinghy4","",""},
{L"诗津 极限快艇","Jetmax","dock_default","jetmax"},
{L"丁卡 水上侯爵","Marquis","dock_default","marquis"},
{L"警用追猎快艇","Predator","",""},
{L"水上枭雄 海鲨摩托艇","Seashark","dock_default","seashark"},
{L"水上枭雄 海鲨摩托艇 (救援用)","Seashark2","",""},
{L"水上枭雄 海鲨摩托艇 (Charged)","Seashark3","",""},
{L"佩嘉西 飙速","Speeder","dock_default","speeder"},
{L"佩嘉西 飙速 (涂装版)","Speeder2","",""},
{L"诗津 思快乐快艇","Squalo","dock_default","squalo"},
{L"潜水艇","Submersible","",""},
{L"海怪 (潜水艇)","Submersible2","dock_default","sub2"},
{L"诗津 向阳号","Suntrap","dock_default","suntrap"},
{L"兰帕达提 公牛 (褐色)","Toro","dock_default","toro"},
{L"兰帕达缇 公牛 (黑色)","Toro2","",""},
{L"诗津 烈阳号","Tropic","dock_default","tropic"},
{L"诗津 烈阳号 (带扶手)","Tropic2","",""},
{L"拖船","Tug","",""}
};
static std::vector<VehiclePreview> Cycles{
{L"BMX","Bmx","pandm_default","bmx"},
{L"巡航者","Cruiser","pandm_default","cruiser"},
{L"极限耐力竞速自行车","Tribike2","pandm_default","tribike2"},
{L"费斯特","Fixter","",""},
{L"先驱者","Scorcher","pandm_default","scorcher"},
{L"特莱塞可竞速自行车","Tribike3","pandm_default","tribike3"},
{L"惠比特竞速自行车","Tribike","pandm_default","tribike"}
};
static std::vector<VehiclePreview> Trains{
{L"缆车","Cablecar","",""},
{L"火车挂车","Freightcont1","",""},
{L"火车挂车带箱","Freightcont2","",""},
{L"火车平板挂车","Freightcar","",""},
{L"火车头","Freight","",""},
{L"火车谷物挂车","Freightgrain","",""},
{L"城市电车 (半个)","Metrotrain","",""},
{L"油罐火车挂车","Tankercar","",""}
};
static std::vector<VehiclePreview> Trailer{
{L"军用坦克", "Armytanker", "", "" },
{L"军用拖车(空)", "Armytrailer", "", "" },
{L"军用拖车(带挂车)", "Armytrailer2", "", "" },
{L"干草捆挂车", "Baletrailer", "", "" },
{L"船挂车", "Boattrailer", "", "" },
{L"油罐挂车", "Docktrailer", "", "" },
{L"平板挂车", "Freighttrailer", "", "" },
{L"谷物挂车", "Graintrailer", "", "" },
{L"房车挂车 (可乘坐)", "Proptrailer", "", "" },
{L"耙子车头", "Raketrailer", "", "" },
{L"油罐挂车 (RON)", "Tanker", "", "" },
{L"油罐挂车 (无字)", "Tanker2", "", "" },
{L"运车挂车 (空)", "Tr2", "", "" },
{L"运船挂车 (带船)", "Tr3", "", "" },
{L"运车挂车 (带车)", "Tr4", "", "" },
{L"平板挂车", "Trailerlogs", "", "" },
{L"挂车 (无箱)", "Trailers", "", "" },
{L"挂车带箱 (Pibwasser)", "Trailers2", "", "" },
{L"挂车带箱 (Big Goods)", "Trailers3", "", "" },
{L"挂车带箱", "Trailers4", "", "" },
{L"微型挂车", "Trailersmall", "", "" },
{L"移动作战中心", "trailerlarge", "", "" },
{L"平板拖车2", "Trflat", "", "" },
{L"挂车厢 (Fame or Shame)", "Tvtrailer", "", "" }
};
static std::vector<VehiclePreview> SUV{
{L"悠游 行者 (CEO)","Baller6","",""},
{L"悠游 行者 2","Baller2","sssa_default","baller2"},
{L"悠游 行者 LE (Armored)","Baller5","",""},
{L"悠游 行者 LE LWB","Baller4","lgm_dlc_apartments","baller4"},
{L"悠游 行者 LE","Baller3","lgm_dlc_apartments","baller3"},
{L"悠游 行者","Baller","",""},
{L"卡林 碧杰 XL","Bjxl","sssa_dlc_battle","bjxl"},
{L"卡尼斯 陆上专家","Seminole","sssa_dlc_heist","seminole"},
{L"亚班尼 骑兵 Mk2","CAVALCADE2","sssa_dlc_business","cavcade2"},
{L"亚班尼 骑兵","CAVALCADE","sssa_default","cavcade"},
{L"威皮 争夺者","Contender","sssa_dlc_stunt","contender"},
{L"贝飞特 迪布达 (亚光黑)","Dubsta2","",""},
{L"贝飞特 迪布达","Dubsta","",""},
{L"皇霸天 哈拔尼禄","Habanero","sssa_dlc_battle","habanero"},
{L"埃努斯 肯特利 S","Huntley","lgm_dlc_business2","huntley"},
{L"深水 FQ 2","fq2","sssa_dlc_battle","fq2"},
{L"绝致 屌王","Granger","sssa_dlc_business","granger"},
{L"冒险家 情欲猎手","Gresley","sssa_dlc_heist","gresley"},
{L"敦追里 追捕者","Landstalker","sssa_dlc_heist","landstalker"},
{L"巨象 爱国者","Patriot","sssa_dlc_battle","patriot"},
{L"卡尼斯 岩魔 (雪地版)","Mesa2","",""},
{L"卡尼斯 岩魔 SUV","Mesa","candc_default","mesa"},
{L"兰帕达缇 诺瓦克","novak","lgm_dlc_vinewood","novak"},
{L"巨象 爱国者加长型礼车","Patriot2","sssa_dlc_battle","patriot2"},
{L"威皮 辐光","Radi","sssa_dlc_business","radi"},
{L"绝品 瑞巴拉 GTS","rebla","lgm_dlc_casinoheist","rebla"},
{L"奥北 小辣椒","Rocoto","sssa_default","rocoto"},
{L"贝飞特 瑟雷诺","Serrano","sssa_dlc_battle","serrano"},
{L"佩嘉西 斗牛","TOROS","lgm_dlc_arena","toros"},
{L"贝飞特 XLS(装甲版)","Xls2","",""},
{L"贝飞特 XLS","Xls","lgm_dlc_executive1","xls"}
};
static std::vector<std::pair<std::wstring, std::vector<VehiclePreview>>> vehiclePreview{
	{L"超跑 >>",Super},
	{L"跑车 >>",Sports},
	{L"经典跑车 >>",SportsClassics},
	{L"轿跑 >>",Coupes},
	{L"肌肉车 >>",Muscle},
	{L"越野车 >>",Offroad},
	{L"摩托车 >>",Motorcycles},
	{L"军用车辆 >>",Military},
	{L"应急车辆 >>",Emergency},
	{L"服务车辆 >>",Service},
	{L"轿车 >>",Sedans},
	{L"工业车辆 >>",Industrial},
	{L"小型车 >>",Compacts},
	{L"商用车 >>",Commercial},
	{L"飞机 >>",Planes},
	{L"多用途车 >>",Utility},
	{L"直升飞机 >>",Helicopters},
	{L"厢式货车 >>",Vans},
	{L"船 >>",Boats},
	{L"自行车 >>",Cycles},
	{L"火车 >>",Trains},
	{L"拖车 >>",Trailer},
	{L"SUV >>",SUV},
};


static unsigned int joaat(std::string input)
{
	unsigned int num1 = 0U;
	for (char c : input)
	{
		unsigned int num2 = num1 + (unsigned int)tolower(c);
		unsigned int num3 = num2 + (num2 << 10);
		num1 = num3 ^ num3 >> 6;
	}
	unsigned int num4 = num1 + (num1 << 3);
	unsigned int num5 = num4 ^ num4 >> 11;
	return num5 + (num5 << 15);
}
