#pragma once
#include<vector>

struct WeaponPreview {
	std::wstring Name;
	char* Weapon;
	char* Pickup;
	char* Model;
};

static std::vector<WeaponPreview> Weapons{
	{L"Advancedrifle", "weapon_advancedrifle", "pickup_weapon_advancedrifle", "w_ar_advancedrifle" },
	{L"Appistol","weapon_appistol","pickup_weapon_appistol","w_pi_appistol" },
	{L"Assaultrifle","weapon_assaultrifle","pickup_weapon_assaultrifle","w_ar_assaultrifle" },
	{L"Assaultshotgun","weapon_assaultshotgun","pickup_weapon_assaultshotgun","w_sg_assaultshotgun" },
	{L"Assaultsmg","weapon_assaultsmg","pickup_weapon_assaultsmg","w_sb_assaultsmg" },
	{L"Autoshotgun","weapon_autoshotgun","pickup_weapon_autoshotgun","w_sg_autoshotgun" },
	{L"Ball","weapon_ball","pickup_weapon_ball","w_am_baseball" },
	{L"Bat","weapon_bat","pickup_weapon_bat","w_me_bat" },
	{L"Battleaxe","weapon_battleaxe","pickup_weapon_battleaxe","w_me_battleaxe" },
	{L"Bottle","weapon_bottle","pickup_weapon_bottle","w_me_bottle" },
	{L"Bullpuprifle","weapon_bullpuprifle","pickup_weapon_bullpuprifle","w_ar_bullpuprifle" },
	{L"Bullpupshotgun","weapon_bullpupshotgun","pickup_weapon_bullpupshotgun","w_sg_bullpupshotgun" },
	{L"Bzgas","weapon_bzgas","pickup_weapon_bzgas","w_ex_grenadesmoke" },
	{L"Carbinerifle","weapon_carbinerifle","pickup_weapon_carbinerifle","w_ar_carbinerifle" },
	{L"Combatmg","weapon_combatmg","pickup_weapon_combatmg","w_mg_combatmg" },
	{L"Combat PDW","weapon_combatpdw","pickup_weapon_combatpdw","w_sb_pdw" },
	{L"Combatpistol","weapon_combatpistol","pickup_weapon_combatpistol","w_pi_combatpistol" },
	{L"Compactlauncher","weapon_compactlauncher","pickup_weapon_compactlauncher","w_lr_compactlauncher" },
	{L"Compactrifle","weapon_compactrifle","pickup_weapon_compactrifle","w_ar_compactrifle" },
	{L"Crowbar","weapon_crowbar","pickup_weapon_crowbar","w_me_crowbar" },
	{L"Dagger","weapon_dagger","pickup_weapon_dagger","w_me_dagger" },
	{L"Dbshotgun","weapon_dbshotgun","pickup_weapon_dbshotgun","w_sg_dbshotgun" },
	{L"Doubleaction","weapon_doubleaction","pickup_weapon_doubleaction","w_pi_doubleaction" },
	{L"Fireextinguisher","weapon_fireextinguisher","pickup_weapon_fireextinguisher","w_am_fire_exting" },
	{L"Firework","weapon_firework","pickup_weapon_firework","w_lr_firework" },
	{L"Flare","weapon_flare","pickup_weapon_flare","w_am_flare" },
	{L"Flaregun","weapon_flaregun","pickup_weapon_flaregun","w_pi_flaregun" },
	{L"Flashlight","weapon_flashlight","pickup_weapon_flashlight","w_me_flashlight" },
	{L"Golfclub","weapon_golfclub","pickup_weapon_golfclub","w_me_gclub" },
	{L"Grenade","weapon_grenade","pickup_weapon_grenade","w_ex_grenadefrag" },
	{L"Grenadelauncher","weapon_grenadelauncher","pickup_weapon_grenadelauncher","w_lr_grenadelauncher" },
	{L"Gusenberg","weapon_gusenberg","pickup_weapon_gusenberg","w_sb_gusenberg" },
	{L"Hammer","weapon_hammer","pickup_weapon_hammer","w_me_hammer" },
	{L"Hatchet","weapon_hatchet","pickup_weapon_hatchet","w_me_hatchet" },
	{L"Heavypistol","weapon_heavypistol","pickup_weapon_heavypistol","w_pi_heavypistol" },
	{L"Heavyshotgun","weapon_heavyshotgun","pickup_weapon_heavyshotgun","w_sg_heavyshotgun" },
	{L"Heavysniper","weapon_heavysniper","pickup_weapon_heavysniper","w_sr_heavysniper" },
	{L"Hominglauncher","weapon_hominglauncher","pickup_weapon_hominglauncher","w_lr_homing" },
	{L"Knife","weapon_knife","pickup_weapon_knife","w_me_knife_01" },
	{L"Knuckle","weapon_knuckle","pickup_weapon_knuckle","w_me_knuckle" },
	{L"Machete","weapon_machete","pickup_weapon_machete","w_me_machete" },
	{L"Machinepistol","weapon_machinepistol","pickup_weapon_machinepistol","w_pi_machinepistol" },
	{L"Marksmanpistol","weapon_marksmanpistol","pickup_weapon_marksmanpistol","w_pi_marksmanpistol" },
	{L"Marksmanrifle","weapon_marksmanrifle","pickup_weapon_marksmanrifle","w_sr_marksmanrifle" },
	{L"MG","weapon_mg","pickup_weapon_mg","w_mg_mg" },
	{L"Microsmg","weapon_microsmg","pickup_weapon_microsmg","w_sb_microsmg" },
	{L"Minigun","weapon_minigun","pickup_weapon_minigun","w_mg_minigun" },
	{L"Minismg","weapon_minismg","pickup_weapon_minismg","w_sb_minismg" },
	{L"Molotov","weapon_molotov","pickup_weapon_molotov","w_ex_molotov" },
	{L"Musket","weapon_musket","pickup_weapon_musket","w_ar_musket" },
	{L"Nightstick","weapon_nightstick","pickup_weapon_nightstick","w_me_nightstick" },
	{L"Petrolcan","weapon_petrolcan","pickup_weapon_petrolcan","w_am_jerrycan" },
	{L"Pipebomb","weapon_pipebomb","pickup_weapon_pipebomb","w_ex_pipebomb" },
	{L"Pistol","weapon_pistol","pickup_weapon_pistol","w_pi_pistol" },
	{L"Pistol50","weapon_pistol50","pickup_weapon_pistol50","w_pi_pistol50" },
	{L"Poolcue","weapon_poolcue","pickup_weapon_poolcue","w_me_poolcue" },
	{L"Proxmine","weapon_proxmine","pickup_weapon_proxmine","w_ex_proxmine" },
	{L"Pumpshotgun","weapon_pumpshotgun","pickup_weapon_pumpshotgun","w_sg_pumpshotgun" },
	{L"Railgun","weapon_railgun","pickup_weapon_railgun","w_ar_railgun" },
	{L"Raycarbine","weapon_raycarbine","pickup_weapon_raycarbine","w_ar_raycarbine" },
	{L"Rayminigun","weapon_rayminigun","pickup_weapon_rayminigun","w_mg_rayminigun" },
	{L"Raypistol","weapon_raypistol","pickup_weapon_raypistol","w_pi_raygun" },
	{L"Revolver","weapon_revolver","pickup_weapon_revolver","w_pi_revolver" },
	{L"RPG","weapon_rpg","pickup_weapon_rpg","w_lr_rpg" },
	{L"Sawnoffshotgun","weapon_sawnoffshotgun","pickup_weapon_sawnoffshotgun","w_sg_sawnoff" },
	{L"SMG","weapon_smg","pickup_weapon_smg","w_sb_smg" },
	{L"Smokegrenade","weapon_smokegrenade","pickup_weapon_smokegrenade","w_ex_grenadesmoke" },
	{L"Sniperrifle","weapon_sniperrifle","pickup_weapon_sniperrifle","w_sr_sniperrifle" },
	{L"Snowball","weapon_snowball","pickup_weapon_snowball","w_ex_snowball" },
	{L"SNS Pistol","weapon_snspistol","pickup_weapon_snspistol","w_pi_sns_pistol " },
	{L"Specialcarbine","weapon_specialcarbine","pickup_weapon_specialcarbine","w_ar_specialcarbine" },
	{L"Stickybomb","weapon_stickybomb","pickup_weapon_stickybomb","w_ex_pe" },
	{L"Stone Hatchet","weapon_stone_hatchet","pickup_weapon_stone_hatchet","w_me_stonehatchet" },
	{L"Stungun","weapon_stungun","pickup_weapon_stungun","w_pi_stungun" },
	{L"Switchblade","weapon_switchblade","pickup_weapon_switchblade","w_me_switchblade" },
	{L"Vintagepistol","weapon_vintagepistol","pickup_weapon_vintagepistol","w_pi_vintage_pistol" },
	{L"Wrench","weapon_wrench","pickup_weapon_wrench","w_me_wrench" },
	{L"Unarmed","weapon_unarmed","pickup_weapon_unarmed","w_me_unarmed" }
};